/** Thiết lập khách hàng — nhóm + trạng thái */
export const customerSettings = {
  title: 'Thiết lập khách hàng',
  tabGroup: 'Nhóm khách hàng',
  tabStatus: 'Trạng thái khách hàng',
  filterCreator: 'Người tạo',
  nhom: {
    title: 'Nhóm khách hàng',
    deleteTitle: 'Xóa nhóm khách hàng',
    deleteMessage: 'Bạn có chắc chắn muốn xóa nhóm khách hàng này không?',
    bulkDeleteMessage: 'Bạn có chắc chắn muốn xóa {{count}} nhóm đã chọn?',
    noExportData: 'Không có dữ liệu để xuất',
    importTemplateName: 'Mau_Import_Nhom_Khach_Hang',
    empty: 'Chưa có nhóm khách hàng',
    emptyHint: 'Hãy tạo nhóm đầu tiên để phân loại khách hàng.',
    loading: 'Đang tải danh sách nhóm...',
    form: {
      editTitle: 'Chỉnh sửa nhóm khách hàng',
      createTitle: 'Thêm nhóm khách hàng',
      editSubtitle: 'Cập nhật thông tin nhóm hiện có',
      createSubtitle: 'Thiết lập nhóm phân loại khách hàng mới',
      generalInfo: 'Thông tin chung',
      name: 'Tên nhóm',
      namePlaceholder: 'VD: VIP, Tiềm năng…',
      description: 'Mô tả',
    },
    store: {
      nameCol: 'Tên nhóm',
      descCol: 'Mô tả',
      creatorCol: 'Người tạo',
      createdCol: 'Ngày tạo',
      updatedCol: 'Cập nhật cuối',
    },
    detail: {
      title: 'Chi tiết nhóm',
      subtitle: 'Nhóm khách hàng',
      systemInfo: 'Thông tin hệ thống',
      createdAt: 'Được tạo lúc',
      updated: 'Cập nhật',
    },
    validation: {
      nameMin: 'Tên nhóm phải có ít nhất 2 ký tự',
      nameMax: 'Tên nhóm tối đa 100 ký tự',
      descMax: 'Mô tả tối đa 500 ký tự',
    },
    toast: {
      createSuccess: 'Tạo nhóm khách hàng thành công',
      updateSuccess: 'Cập nhật nhóm thành công',
      deleteSuccess: 'Đã xóa {{count}} nhóm khách hàng',
      importSuccess: 'Đã nhập {{count}} nhóm khách hàng',
    },
    exportName: 'Tên nhóm',
    exportDesc: 'Mô tả',
  },
  trangThai: {
    title: 'Trạng thái khách hàng',
    deleteTitle: 'Xóa trạng thái khách hàng',
    deleteMessage: 'Bạn có chắc chắn muốn xóa trạng thái này không?',
    bulkDeleteMessage: 'Bạn có chắc chắn muốn xóa {{count}} trạng thái đã chọn?',
    noExportData: 'Không có dữ liệu để xuất',
    importTemplateName: 'Mau_Import_Trang_Thai_Khach_Hang',
    empty: 'Chưa có trạng thái khách hàng',
    emptyHint: 'Hãy tạo trạng thái đầu tiên cho quy trình chăm sóc.',
    loading: 'Đang tải danh sách trạng thái...',
    form: {
      editTitle: 'Chỉnh sửa trạng thái khách hàng',
      createTitle: 'Thêm trạng thái khách hàng',
      editSubtitle: 'Cập nhật thông tin trạng thái hiện có',
      createSubtitle: 'Thiết lập trạng thái mới trong quy trình',
      generalInfo: 'Thông tin chung',
      name: 'Tên trạng thái',
      namePlaceholder: 'VD: Mới, Đang chăm sóc…',
      description: 'Mô tả',
    },
    store: {
      nameCol: 'Tên trạng thái',
      descCol: 'Mô tả',
      creatorCol: 'Người tạo',
      createdCol: 'Ngày tạo',
      updatedCol: 'Cập nhật cuối',
    },
    detail: {
      title: 'Chi tiết trạng thái',
      subtitle: 'Trạng thái khách hàng',
      systemInfo: 'Thông tin hệ thống',
      createdAt: 'Được tạo lúc',
      updated: 'Cập nhật',
    },
    validation: {
      nameMin: 'Tên trạng thái phải có ít nhất 2 ký tự',
      nameMax: 'Tên trạng thái tối đa 100 ký tự',
      descMax: 'Mô tả tối đa 500 ký tự',
    },
    toast: {
      createSuccess: 'Tạo trạng thái khách hàng thành công',
      updateSuccess: 'Cập nhật trạng thái thành công',
      deleteSuccess: 'Đã xóa {{count}} trạng thái khách hàng',
      importSuccess: 'Đã nhập {{count}} trạng thái khách hàng',
    },
    exportName: 'Tên trạng thái',
    exportDesc: 'Mô tả',
  },
} as const;
