/** Nhân viên */
export const employee = {
  "title": "Nhân viên",
  "tabList": "Danh sách",
  "tabStats": "Thống kê",
  "name": "Họ tên",
  "code": "Mã NV",
  "email": "Email",
  "phone": "Điện thoại",
  "gender": "Giới tính",
  "hireDate": "Ngày vào làm",
  "position": "Chức vụ",
  "department": "Phòng ban",
  "division": "Bộ phận",
  "level": "Cấp bậc",
  "status": "Trạng thái",
  "birthDate": "Ngày sinh",
  "contractType": "Loại HĐ",
  "workplace": "Nơi làm việc",
  "province": "Tỉnh/TP",
  "education": "Trình độ",
  "idCard": "CCCD",
  "createdAt": "Ngày tạo",
  "positionDepartment": "Chức vụ / Phòng ban",
  "columnHeader": {
    "sortAsc": "Sắp xếp A đến Z",
    "sortDesc": "Sắp xếp Z đến A",
    "searchPlaceholder": "Lọc",
  },
  "rowActions": {
    "more": "Thao tác khác",
    "popupBlocked": "Không mở được tab mới",
    "popupBlockedHint": "Trình duyệt có thể đã chặn cửa sổ mới. Cho phép popup cho trang này hoặc mở đường dẫn hồ sơ trong tab hiện tại.",
    "noPhone": "Chưa có số điện thoại",
  },
  "unassigned": "Chưa gán",
  "searchPlaceholder": "Tìm theo tên, mã NV, email…",
  "deleteConfirmTitle": "Xóa nhân viên?",
  "deleteConfirmMessage": "Bạn có chắc muốn xóa nhân viên",
  "deleteConfirmNote": "Bạn có thể hoàn tác trong vài giây.",
  "statusChangeTitle": "Cập nhật trạng thái",
  "statusChangeMessage": "Chọn trạng thái mới cho nhân viên",
  "bulkDeleteTitle": "Xóa nhiều nhân viên",
  "bulkDeleteMessage": "Bạn đang chọn xóa {{count}} hồ sơ nhân sự. Bạn có thể hoàn tác trong vài giây.",
  "bulkStatusTitle": "Cập nhật trạng thái hàng loạt",
  "bulkStatusMessage": "Chuyển trạng thái {{count}} nhân viên sang",
  "importSuccess": "Import {{count}} nhân viên thành công",
  "importTemplateName": "Mau_Import_Nhan_Vien",
  "exportFileName": "Danh_Sach_Nhan_Vien",
  "statusActive": "Đang làm việc",
  "statusProbation": "Thử việc",
  "statusLeave": "Nghỉ phép",
  "statusResigned": "Đã nghỉ việc",
  "statusActiveShort": "Đang hoạt động",
  "statusInactiveShort": "Ngưng hoạt động",
  "genderMale": "Nam",
  "genderFemale": "Nữ",
  "genderOther": "Khác",
  "maritalSingle": "Độc thân",
  "maritalMarried": "Đã kết hôn",
  "maritalDivorced": "Ly hôn",
  "maritalWidowed": "Góa",
  "eduHighSchool": "THPT",
  "eduCollege": "Trung cấp",
  "eduAssociate": "Cao đẳng",
  "eduBachelor": "Đại học",
  "eduMaster": "Thạc sĩ",
  "eduDoctor": "Tiến sĩ",
  "contractProbation": "Thử việc",
  "contractFixed": "Có thời hạn",
  "contractIndefinite": "Không thời hạn",
  "contractSeasonal": "Thời vụ",
  "relFather": "Cha",
  "relMother": "Mẹ",
  "relWife": "Vợ",
  "relHusband": "Chồng",
  "relSibling": "Anh/Chị/Em",
  "relOther": "Khác",
  "resignQuit": "Nghỉ việc",
  "resignContractEnd": "Hết hợp đồng",
  "resignFired": "Sa thải",
  "resignAgreement": "Thỏa thuận",
  "resignOther": "Khác",
  "form": {
    "editTitle": "Chỉnh sửa Hồ sơ",
    "createTitle": "Thêm Nhân viên mới",
    "editSubtitle": "ID:",
    "createSubtitle": "Thiết lập thông tin nhân sự mới vào hệ thống",
    "validationError": "Vui lòng điền đầy đủ các trường bắt buộc (*) và kiểm tra lỗi bên dưới.",
    "personalInfo": "Thông tin cá nhân",
    "identityInfo": "Giấy tờ & địa chỉ",
    "avatar": "Ảnh đại diện",
    "avatarHint": "Ảnh chân dung, khung tròn · Tối đa 10MB",
    "fullName": "Họ và tên",
    "gender": "Giới tính",
    "employeeCode": "Mã nhân viên",
    "employeeCodePlaceholder": "VD: NV001",
    "birthDate": "Ngày sinh",
    "idCard": "CMND/CCCD",
    "idCardPlaceholder": "VD: 012345678901",
    "idCardHint": "Đủ 12 chữ số, không khoảng trắng.",
    "idIssueDate": "Ngày cấp CCCD",
    "idIssuePlace": "Nơi cấp",
    "idIssuePlaceholder": "VD: Cục Cảnh sát QLHC về TTXH",
    "permanentAddress": "Địa chỉ thường trú",
    "permanentAddressPlaceholder": "Số nhà, đường, phường/xã, tỉnh/thành",
    "currentAddress": "Chỗ ở hiện tại",
    "currentAddressHint": "Chỉ nhập nếu khác địa chỉ thường trú.",
    "nationality": "Quốc tịch",
    "ethnicity": "Dân tộc",
    "religion": "Tôn giáo",
    "workInfo": "Thông tin công việc",
    "additionalSectionsSummary": "Thông tin bổ sung (liên hệ, địa chỉ, gia đình, học vấn, tài chính, bảo hiểm)",
    "stepNext": "Tiếp theo",
    "stepCoreLabel": "Cốt lõi",
    "stepCoreDesc": "Cá nhân và công việc",
    "stepContactLabel": "Liên hệ & gia đình",
    "stepContactDesc": "Liên hệ, địa chỉ, người thân",
    "stepExtraLabel": "Học vấn & pháp lý",
    "stepExtraDesc": "Học vấn, ngân hàng, bảo hiểm",
    "position": "Chức vụ",
    "positionPlaceholder": "Chọn chức vụ",
    "department": "Phòng ban",
    "division": "Bộ phận",
    "departmentAutoHint": "Tự động theo chức vụ đã chọn.",
    "level": "Cấp bậc",
    "levelPlaceholder": "Chọn cấp bậc",
    "branch": "Chi nhánh làm việc",
    "branchPlaceholder": "Chọn chi nhánh",
    "hireDate": "Ngày vào làm",
    "officialDate": "Ngày chính thức",
    "resignationDate": "Ngày nghỉ việc",
    "resignationReason": "Lý do nghỉ",
    "resignationReasonPlaceholder": "Chọn lý do nghỉ",
    "hometown": "Quê quán",
    "bankAccountHolder": "Chủ tài khoản",
    "bankAccountHolderHint": "Ghi đúng tên in trên thẻ/sổ ngân hàng.",
    "contractType": "Loại hợp đồng",
    "contractTypePlaceholder": "Chọn loại hợp đồng",
    "contractEndDate": "Ngày hết hạn HĐ",
    "workplace": "Nơi làm việc",
    "workplacePlaceholder": "VD: Trụ sở chính, Chi nhánh Hà Nội",
    "workStatus": "Trạng thái làm việc",
    "workStatusPlaceholder": "Chọn trạng thái làm việc",
    "authAccount": "Tài khoản hệ thống",
    "loginName": "Tên đăng nhập",
    "loginNamePlaceholder": "VD: nguyenvana",
    "loginNameHint": "Dùng để đăng nhập — không phải email công việc.",
    "authEmailPreview": "Email đăng nhập (Auth)",
    "authEmailPreviewHint": "Hệ thống tự tạo từ tên đăng nhập + @gmail.com",
    "tempPassword": "Mật khẩu tạm",
    "tempPasswordHint": "Tối thiểu 1 ký tự (số hoặc chữ) · Nhân viên phải đổi khi đăng nhập lần đầu.",
    "resetPassword": "Đặt lại mật khẩu",
    "newTempPassword": "Mật khẩu mới",
    "loginChangeWarning": "Tài khoản Auth cũ sẽ bị xóa. Nhân viên đăng nhập bằng tên mới và mật khẩu tạm bên dưới.",
    "createAuthOnEditHint": "Nhân viên chưa có tài khoản — nhập tên đăng nhập và mật khẩu tạm để tạo.",
    "resetPasswordSuccess": "Đã đặt lại mật khẩu — nhân viên cần đổi khi đăng nhập.",
    "contactInfo": "Thông tin liên hệ",
    "workEmail": "Email công việc",
    "workEmailPlaceholder": "VD: ten@congty.vn",
    "personalEmail": "Email cá nhân",
    "personalEmailPlaceholder": "VD: ten@gmail.com",
    "phoneNumber": "Số điện thoại",
    "phonePlaceholder": "VD: 0901234567",
    "emergencyContact": "Người liên hệ khẩn cấp",
    "emergencyPhone": "SĐT khẩn cấp",
    "relationship": "Quan hệ",
    "relationshipPlaceholder": "Chọn quan hệ",
    "address": "Địa chỉ",
    "province": "Tỉnh/Thành phố",
    "district": "Quận/Huyện",
    "ward": "Phường/Xã",
    "detailAddress": "Địa chỉ chi tiết",
    "detailAddressPlaceholder": "Số nhà, đường, tổ/ấp",
    "tempAddress": "Địa chỉ tạm trú",
    "tempAddressHint": "Chỉ nhập nếu khác địa chỉ thường trú.",
    "familyInfo": "Hôn nhân & Gia đình",
    "maritalStatus": "Tình trạng hôn nhân",
    "maritalPlaceholder": "Chọn tình trạng hôn nhân",
    "dependents": "Số người phụ thuộc",
    "educationInfo": "Học vấn & Chứng chỉ",
    "educationLevel": "Trình độ học vấn",
    "educationPlaceholder": "Chọn trình độ học vấn",
    "major": "Chuyên ngành",
    "majorPlaceholder": "VD: Công nghệ thông tin",
    "school": "Trường đào tạo",
    "schoolPlaceholder": "VD: Đại học Bách Khoa TP.HCM",
    "graduationYear": "Năm tốt nghiệp",
    "certificates": "Chứng chỉ bổ sung",
    "certificatesPlaceholder": "VD: AWS, PMP, IELTS…",
    "financialInfo": "Tài chính & Ngân hàng",
    "bankAccount": "Số tài khoản",
    "bankAccountPlaceholder": "VD: 0123456789",
    "bankName": "Tên ngân hàng",
    "bankNamePlaceholder": "VD: Vietcombank, BIDV",
    "bankBranch": "Chi nhánh",
    "bankBranchPlaceholder": "VD: Chi nhánh Sở Giao Dịch",
    "taxId": "Mã số thuế cá nhân",
    "taxIdPlaceholder": "VD: 0123456789",
    "taxIdHint": "10 chữ số (hoặc 13 nếu có mã đơn vị).",
    "insuranceInfo": "Bảo hiểm",
    "socialInsurance": "Số BHXH",
    "socialInsurancePlaceholder": "VD: 0123456789",
    "healthInsurance": "Số BHYT",
    "healthInsurancePlaceholder": "VD: HS4010123456789",
    "healthInsuranceHint": "15 ký tự in trên thẻ BHYT.",
    "insuranceDate": "Ngày tham gia BH",
    "medicalFacility": "Nơi đăng ký KCB",
    "medicalFacilityPlaceholder": "VD: Bệnh viện Đại học Y Dược"
  },
  "detail": {
    "title": "Hồ sơ Nhân sự",
    "subtitle": "Mã NV:",
    "tabInfo": "Thông tin",
    "tabContracts": "Hợp đồng",
    "tabDecisions": "Quyết định",
    "contractsSection": "Hợp đồng",
    "contractsAdd": "Thêm hợp đồng",
    "contractsEmpty": "Chưa có hợp đồng",
    "contractsEmptyHint": "Hãy thêm hợp đồng đầu tiên cho nhân viên này.",
    "contractsForbidden": "Bạn không có quyền xem hợp đồng.",
    "decisionsComingSoon": "Quyết định đang được phát triển",
    "decisionsComingSoonHint": "Module quyết định sẽ sớm có mặt tại đây.",
    "changeStatus": "Trạng thái",
    "print": "In hồ sơ",
    "changePassword": "Đổi MK",
    "sendEmail": "Gửi Email",
    "callPhone": "Gọi điện",
    "permission": "Phân quyền",
    "personalInfo": "Thông tin cá nhân",
    "identityInfo": "Giấy tờ & địa chỉ",
    "fullName": "Họ tên",
    "birthDate": "Ngày sinh",
    "gender": "Giới tính",
    "idCard": "CMND/CCCD",
    "idIssueDate": "Ngày cấp",
    "idIssuePlace": "Nơi cấp",
    "permanentAddress": "Địa chỉ thường trú",
    "currentAddress": "Chỗ ở hiện tại",
    "nationality": "Quốc tịch",
    "ethnicity": "Dân tộc",
    "religion": "Tôn giáo",
    "workInfo": "Thông tin công việc",
    "employeeCode": "Mã nhân viên",
    "position": "Chức vụ",
    "department": "Phòng ban",
    "division": "Bộ phận",
    "level": "Cấp bậc",
    "hireDate": "Ngày vào làm",
    "officialDate": "Ngày chính thức",
    "resignationDate": "Ngày nghỉ việc",
    "resignationReason": "Lý do nghỉ",
    "hometown": "Quê quán",
    "bankAccountHolder": "Chủ tài khoản",
    "tenure": "Thâm niên",
    "contractType": "Loại hợp đồng",
    "contractEndDate": "Ngày hết hạn HĐ",
    "workplace": "Nơi làm việc",
    "authAccount": "Tài khoản hệ thống",
    "loginName": "Tên đăng nhập",
    "authEmail": "Email đăng nhập (Auth)",
    "accountActive": "Tài khoản hoạt động",
    "accountInactive": "Tài khoản vô hiệu",
    "mustChangePassword": "Cần đổi mật khẩu lần đầu",
    "contactInfo": "Thông tin liên hệ",
    "workEmail": "Email công việc",
    "personalEmail": "Email cá nhân",
    "phone": "Điện thoại",
    "emergencyContact": "Người liên hệ khẩn cấp",
    "emergencyPhone": "SĐT khẩn cấp",
    "relationship": "Quan hệ",
    "address": "Địa chỉ",
    "province": "Tỉnh/Thành phố",
    "district": "Quận/Huyện",
    "ward": "Phường/Xã",
    "detailAddress": "Địa chỉ chi tiết",
    "tempAddress": "Địa chỉ tạm trú",
    "familyInfo": "Hôn nhân & Gia đình",
    "maritalStatus": "Tình trạng hôn nhân",
    "dependents": "Số người phụ thuộc",
    "educationInfo": "Học vấn & Chứng chỉ",
    "educationLevel": "Trình độ học vấn",
    "major": "Chuyên ngành",
    "school": "Trường đào tạo",
    "graduationYear": "Năm tốt nghiệp",
    "certificates": "Chứng chỉ bổ sung",
    "financialInfo": "Tài chính & Ngân hàng",
    "bankAccount": "Số tài khoản",
    "bankName": "Ngân hàng",
    "bankBranch": "Chi nhánh",
    "taxId": "Mã số thuế cá nhân",
    "insuranceInfo": "Bảo hiểm",
    "socialInsurance": "Số BHXH",
    "healthInsurance": "Số BHYT",
    "insuranceDate": "Ngày tham gia BH",
    "medicalFacility": "Nơi đăng ký KCB",
    "systemInfo": "Thông tin hệ thống",
    "createdDate": "Ngày tạo",
    "createdBy": "Người tạo",
    "lastUpdated": "Cập nhật lần cuối",
    "updatedBy": "Người cập nhật"
  },
  "bulk": {
    "title": "Chỉnh sửa hàng loạt",
    "subtitle": "nhân viên được chọn",
    "applyButton": "Áp dụng cho {{count}} nhân viên",
    "selectedLabel": "Nhân viên được chọn:",
    "warning": "Chỉ các trường được đánh dấu tick mới được cập nhật. Các trường khác giữ nguyên giá trị hiện tại.",
    "workSection": "Phân bổ công việc",
    "changeDepartment": "Thay đổi Phòng ban",
    "changeBranch": "Thay đổi Chi nhánh làm việc",
    "changePosition": "Thay đổi Chức vụ",
    "changeLevel": "Thay đổi Cấp bậc",
    "contractSection": "Hợp đồng & Trạng thái",
    "changeContract": "Thay đổi Loại hợp đồng",
    "changeStatus": "Thay đổi Trạng thái",
    "confirmTitle": "Xác nhận chỉnh sửa hàng loạt",
    "confirmMessage": "Bạn sắp áp dụng thay đổi cho {{count}} nhân viên. Hành động này không thể hoàn tác."
  },
  "bulkPassword": {
    "title": "Đặt lại mật khẩu hàng loạt",
    "subtitle": "{{count}} nhân viên được chọn",
    "apply": "Đặt lại mật khẩu",
    "hint": "Tối thiểu {{count}} ký tự.",
    "minLength": "Mật khẩu tối thiểu {{count}} ký tự",
    "warning": "Cả {{count}} nhân viên sẽ dùng CHUNG mật khẩu tạm này và bắt buộc đổi ở lần đăng nhập kế tiếp. Hãy gửi mật khẩu riêng cho từng người, không thông báo chung.",
    "noLoginHint": "{{count}} nhân viên chưa có tài khoản đăng nhập sẽ được bỏ qua.",
    "success": "Đã đặt lại mật khẩu cho {{count}} nhân viên",
    "skipped": "Bỏ qua {{count}} nhân viên chưa có tài khoản đăng nhập",
    "confirmTitle": "Xác nhận đặt lại mật khẩu hàng loạt",
    "confirmMessage": "Bạn sắp đặt lại mật khẩu cho {{count}} nhân viên bằng 1 mật khẩu tạm dùng chung. Hành động này không thể hoàn tác."
  },
  "bulkStatus": {
    "trigger": "Đổi trạng thái"
  },
  "toolbar": {
    "department": "Phòng ban",
    "position": "Chức vụ",
    "status": "Trạng thái",
    "gender": "Giới tính",
    "branch": "Chi nhánh",
    "bulkEdit": "Chỉnh sửa hàng loạt",
    "editCount": "Sửa {{count}}",
    "bulkEditDesc": "Cập nhật {{count}} nhân viên đã chọn",
    "importDesc": "Nhập nhân viên từ file Excel",
    "exportDesc": "Xuất danh sách ra file Excel",
    "importData": "Import dữ liệu",
    "exportData": "Export dữ liệu"
  },
  "stats": {
    "department": "Phòng ban",
    "status": "Trạng thái",
    "exportReport": "Xuất báo cáo",
    "loading": "Đang tải thống kê...",
    "exporting": "Đang xuất...",
    "selectFormat": "Chọn định dạng",
    "dataAndMeta": "Số liệu + metadata",
    "printReport": "Báo cáo in",
    "kpiOptions": "Tùy chọn KPI",
    "showKpi": "Hiển thị KPI",
    "totalEmployees": "Tổng nhân viên",
    "working": "Đang làm việc",
    "probation": "Thử việc",
    "leaveResigned": "Nghỉ việc / phép",
    "noData": "Không có dữ liệu",
    "noDataHint": "Thử bỏ bớt bộ lọc hoặc đổi khoảng thời gian để xem kết quả.",
    "noEmployeeInPeriod": "Chưa có nhân viên trong khoảng thời gian này.",
    "clearFilters": "Xóa bộ lọc",
    "comparedLastMonth": "So với tháng trước",
    "workingShort": "Đang làm",
    "departmentChart": "Phân bổ theo phòng ban",
    "statusChart": "Trạng thái nhân sự",
    "quantity": "Số lượng",
    "trendChart": "Xu hướng tuyển dụng (12 tháng)",
    "newHires": "Tuyển mới",
    "genderChart": "Tỷ lệ giới tính",
    "departmentTable": "Thống kê theo phòng ban",
    "total": "Tổng",
    "leave": "Nghỉ",
    "activeRate": "Tỷ lệ HĐ",
    "exportSuccess": "Xuất báo cáo Excel thành công",
    "exportSuccessExcel": "Xuất báo cáo Excel thành công",
    "exportSuccessPdf": "Xuất báo cáo PDF thành công",
    "exportSuccessDesc": "Báo cáo đã được tải về.",
    "exportError": "Xuất báo cáo thất bại",
    "grandTotal": "Tổng cộng",
    "dateRangePlaceholder": "Khoảng thời gian",
    "dateRange": {
      "week": "Tuần",
      "month": "Tháng",
      "quarter": "Quý",
      "year": "Năm",
      "custom": "Tùy chọn"
    },
    "preset": {
      "all": "Tất cả",
      "thisWeek": "Tuần này",
      "lastWeek": "Tuần trước",
      "last7Days": "7 ngày qua",
      "thisMonth": "Tháng này",
      "lastMonth": "Tháng trước",
      "last30Days": "30 ngày qua",
      "thisQuarter": "Quý này",
      "lastQuarter": "Quý trước",
      "last6Months": "6 tháng qua",
      "thisYear": "Năm nay",
      "lastYear": "Năm trước",
      "custom": "Tùy chọn"
    }
  },
  "validation": {
    "codeRequired": "Mã nhân viên là bắt buộc",
    "nameMin": "Họ tên phải có ít nhất 2 ký tự",
    "emailInvalid": "Địa chỉ email không hợp lệ",
    "phoneRequired": "Số điện thoại là bắt buộc",
    "phoneInvalid": "SĐT không hợp lệ (VD: 0901234567)",
    "positionRequired": "Vui lòng chọn chức vụ",
    "positionNoDepartment": "Chức vụ chưa gán phòng ban — vui lòng cập nhật danh mục chức vụ",
    "departmentRequired": "Phòng ban được tự động từ chức vụ — vui lòng chọn chức vụ",
    "departmentMismatch": "Phòng ban không khớp với chức vụ đã chọn",
    "hireDateInvalid": "Ngày vào làm không hợp lệ",
    "ageMin": "Nhân viên phải đủ 16 tuổi trở lên",
    "idCardLength": "CCCD phải có đúng 12 chữ số",
    "personalEmailInvalid": "Email cá nhân không hợp lệ",
    "loginNameRequired": "Tên đăng nhập là bắt buộc",
    "loginNameInvalid": "Tên đăng nhập: 3–32 ký tự, chữ thường, số, dấu chấm, gạch dưới hoặc gạch ngang",
    "loginNameDuplicate": "Tên đăng nhập đã được sử dụng bởi nhân viên khác",
    "loginNameChecking": "Đang kiểm tra tên đăng nhập…",
    "tempPasswordMin": "Mật khẩu tạm phải có ít nhất 1 ký tự (số hoặc chữ)",
    "emergencyPhoneInvalid": "SĐT khẩn cấp không hợp lệ",
    "resignationDateRequired": "Ngày nghỉ việc là bắt buộc khi trạng thái Nghỉ việc",
    "taxIdLength": "Mã số thuế phải có 10 hoặc 13 chữ số",
    "contractEndRequired": "Hợp đồng có thời hạn phải có ngày hết hạn",
    "genderInvalid": "Giới tính không hợp lệ (Nam, Nữ, Khác)",
    "statusInvalid": "Trạng thái nhân viên không hợp lệ"
  },
  "import": {
    "missingRequired": "Thiếu mã, họ tên hoặc email"
  },
  "toast": {
    "createSuccess": "Thêm nhân viên thành công",
    "updateSuccess": "Cập nhật thông tin thành công",
    "statusUpdateSuccess": "Đã cập nhật trạng thái {{count}} nhân viên",
    "bulkUpdateSuccess": "Đã cập nhật {{count}} nhân viên",
    "deleteSuccess": "Đã xóa thành công {{count}} nhân viên",
    "deleteCount": "Đã xóa {{count}} nhân viên",
    "undo": "Hoàn tác",
    "undoSuccess": "Đã hoàn tác xóa",
    "importSuccess": "Import {{count}} nhân viên thành công"
  },
  "service": {
    "notFound": "Nhân viên không tồn tại",
    "restoreUnsupported": "Không hoàn tác được: nhân viên đã bị xóa vĩnh viễn khỏi cơ sở dữ liệu"
  },
  "pdf": {
    "title": "HỒ SƠ NHÂN SỰ",
    "code": "Mã NV:",
    "personalInfo": "THÔNG TIN CÁ NHÂN",
    "workInfo": "THÔNG TIN CÔNG VIỆC",
    "contactInfo": "THÔNG TIN LIÊN HỆ",
    "address": "ĐỊA CHỈ",
    "familyInfo": "HÔN NHÂN & GIA ĐÌNH",
    "educationInfo": "HỌC VẤN & CHỨNG CHỈ",
    "financialInfo": "TÀI CHÍNH & NGÂN HÀNG",
    "insuranceInfo": "BẢO HIỂM",
    "printedAt": "In lúc:",
    "photoPlaceholder": "Ảnh 3×4",
    "signPreparer": "Người lập",
    "signReviewer": "Người kiểm tra",
    "signRelated": "Người liên quan",
    "signApprover": "Phê duyệt",
    "signHint": "(Ký, ghi rõ họ tên)"
  },
  "profile": {
    "notFound": "Không tìm thấy hồ sơ nhân viên.",
    "loadError": "Lỗi tải hồ sơ nhân viên.",
    "print": "In",
    "download": "Tải"
  },
  "export": {
    "doc": "Word (.docx)",
    "excel": "Excel (.xlsx)",
    "pdf": "PDF",
    "failed": "Không tải được tệp",
    "printFallback": "Chọn \"Lưu thành PDF\" trong hộp thoại in"
  },
  "report": {
    "title": "Báo cáo thống kê nhân sự",
    "period": "Khoảng thời gian",
    "departmentFilter": "Bộ lọc phòng ban",
    "statusFilter": "Bộ lọc trạng thái",
    "allFilter": "Tất cả",
    "exportDate": "Ngày xuất",
    "indicator": "Chỉ số",
    "value": "Giá trị",
    "ratio": "Tỷ lệ",
    "overviewSheet": "Tổng quan",
    "byDepartmentSheet": "Theo phòng ban",
    "pdfTitle": "BÁO CÁO THỐNG KÊ NHÂN SỰ",
    "pdfPeriod": "Khoảng thời gian:",
    "pdfExportDate": "Xuất ngày:",
    "pdfDepartment": "Phòng ban:",
    "pdfStatus": "Trạng thái:",
    "pdfByDepartment": "Thống kê theo phòng ban",
    "activeRatePercent": "Tỷ lệ HĐ (%)"
  },
  "store": {
    "codeCol": "Mã NV",
    "nameCol": "Họ và tên",
    "positionDeptCol": "Chức vụ / Phòng ban",
    "positionCol": "Chức vụ",
    "emailCol": "Email",
    "phoneCol": "SĐT",
    "hireDateCol": "Ngày vào",
    "genderCol": "Giới tính",
    "statusCol": "Trạng thái",
    "birthDateCol": "Ngày sinh",
    "departmentCol": "Phòng ban",
    "divisionCol": "Bộ phận",
    "levelCol": "Cấp bậc",
    "contractCol": "Loại HĐ",
    "branchCol": "Chi nhánh",
    "workplaceCol": "Nơi làm việc",
    "provinceCol": "Tỉnh/TP",
    "educationCol": "Trình độ",
    "idCardCol": "CCCD",
    "createdCol": "Ngày tạo"
  }
} as const;
