/** Hợp đồng nhân sự */
export const contract = {
  title: 'Hợp đồng',
  deleteTitle: 'Xóa hợp đồng',
  deleteMessage: 'Bạn có chắc chắn muốn xóa hợp đồng này không?',
  bulkDeleteMessage: 'Bạn có chắc chắn muốn xóa {{count}} hợp đồng đã chọn?',
  noExportData: 'Không có dữ liệu để xuất',
  empty: 'Chưa có hợp đồng',
  emptyHint: 'Hãy tạo hợp đồng đầu tiên cho nhân sự.',
  loading: 'Đang tải danh sách hợp đồng...',
  filterType: 'Loại hợp đồng',
  filterStatus: 'Trạng thái',
  filterDepartment: 'Phòng ban',
  form: {
    editTitle: 'Chỉnh sửa hợp đồng',
    createTitle: 'Thêm hợp đồng',
    editSubtitle: 'Cập nhật thông tin hợp đồng hiện có',
    createSubtitle: 'Tạo hợp đồng mới cho nhân sự',
    generalInfo: 'Thông tin hợp đồng',
    partyInfo: 'Nhân sự & vị trí',
    salaryInfo: 'Lương & điều kiện làm việc',
    noteInfo: 'Ghi chú',
    type: 'Loại hợp đồng',
    typePlaceholder: 'Chọn loại hợp đồng',
    code: 'Mã hợp đồng',
    codePlaceholder: 'VD: HD-CT-0001',
    signDate: 'Ngày ký',
    effectiveDate: 'Ngày hiệu lực',
    endDate: 'Ngày kết thúc',
    employee: 'Nhân viên',
    employeePlaceholder: 'Chọn nhân viên',
    position: 'Chức vụ',
    positionPlaceholder: 'Chọn chức vụ',
    department: 'Phòng ban',
    departmentPlaceholder: 'Chọn phòng ban',
    salary: 'Mức lương',
    salaryPlaceholder: 'VD: 10.000.000 đ/tháng',
    salaryMode: 'Hình thức trả lương',
    salaryModePlaceholder: 'Chọn hình thức trả lương',
    otherBenefits: 'Chế độ khác',
    otherBenefitsPlaceholder: 'BHXH, BHYT, phụ cấp, thưởng…',
    workplace: 'Nơi làm việc',
    workplacePlaceholder: 'VD: Văn phòng công ty',
    workingTime: 'Thời gian làm việc',
    workingTimePlaceholder: 'VD: Thứ 2 - Thứ 7, 08:00 - 17:00',
    otherNotes: 'Lưu ý khác',
    otherNotesPlaceholder: 'Các điều khoản, lưu ý riêng…',
    note: 'Ghi chú',
    noteHint: 'Chỉ hiển thị nội bộ, không in trên hợp đồng.',
    status: 'Trạng thái',
  },
  store: {
    codeCol: 'Mã hợp đồng',
    typeCol: 'Loại',
    employeeCol: 'Nhân viên',
    departmentCol: 'Phòng ban',
    signDateCol: 'Ngày ký',
    effectiveDateCol: 'Ngày hiệu lực',
    endDateCol: 'Ngày kết thúc',
    salaryCol: 'Mức lương',
    statusCol: 'Trạng thái',
    creatorCol: 'Người tạo',
    updatedCol: 'Cập nhật cuối',
  },
  detail: {
    title: 'Chi tiết hợp đồng',
    subtitle: 'Hồ sơ hợp đồng nhân sự',
    print: 'Xem / In hợp đồng',
    generalInfo: 'Thông tin hợp đồng',
    partyInfo: 'Nhân sự & vị trí',
    salaryInfo: 'Lương & điều kiện làm việc',
    noteInfo: 'Ghi chú',
    systemInfo: 'Thông tin hệ thống',
    createdAt: 'Được tạo lúc',
    updated: 'Cập nhật',
  },
  validation: {
    codeMin: 'Mã hợp đồng phải có ít nhất 2 ký tự',
    codeMax: 'Mã hợp đồng tối đa 50 ký tự',
    signDateRequired: 'Vui lòng chọn ngày ký',
    effectiveDateRequired: 'Vui lòng chọn ngày hiệu lực',
    endDateAfterEffective: 'Ngày kết thúc phải sau ngày hiệu lực',
    employeeRequired: 'Vui lòng chọn nhân viên',
    positionRequired: 'Vui lòng chọn chức vụ',
    departmentRequired: 'Vui lòng chọn phòng ban',
    salaryRequired: 'Vui lòng nhập mức lương',
    salaryMax: 'Mức lương tối đa 200 ký tự',
    textMax: 'Nội dung quá dài',
  },
  toast: {
    createSuccess: 'Tạo hợp đồng thành công',
    updateSuccess: 'Cập nhật hợp đồng thành công',
    deleteSuccess: 'Đã xóa {{count}} hợp đồng',
  },
  export: {
    code: 'Mã hợp đồng',
    type: 'Loại hợp đồng',
    employee: 'Nhân viên',
    department: 'Phòng ban',
    position: 'Chức vụ',
    signDate: 'Ngày ký',
    effectiveDate: 'Ngày hiệu lực',
    endDate: 'Ngày kết thúc',
    salary: 'Mức lương',
    salaryMode: 'Hình thức trả lương',
    status: 'Trạng thái',
  },
  print: {
    title: 'Hợp đồng lao động',
    documentTitleProbation: 'HỢP ĐỒNG THỬ VIỆC',
    documentTitleOfficial: 'HỢP ĐỒNG LAO ĐỘNG',
    close: 'Đóng',
    print: 'In',
    download: 'Tải xuống',
    exportDoc: 'Word (.doc)',
    exportPdf: 'PDF',
    exportFailed: 'Không tải được tệp hợp đồng',
    loadError: 'Không tải được hợp đồng.',
    notFound: 'Không tìm thấy hợp đồng.',
    popupBlocked: 'Trình duyệt đã chặn cửa sổ in',
    popupBlockedHint: 'Vui lòng cho phép popup để mở trang in hợp đồng.',
    printedAt: 'In lúc:',
    number: 'Số:',
    section: {
      party: 'Thông tin nhân sự',
      terms: 'Điều khoản hợp đồng',
      salary: 'Lương & điều kiện làm việc',
      note: 'Ghi chú',
    },
    field: {
      employee: 'Họ và tên',
      department: 'Phòng ban',
      position: 'Chức vụ',
      type: 'Loại hợp đồng',
      code: 'Mã hợp đồng',
      signDate: 'Ngày ký',
      effectiveDate: 'Ngày hiệu lực',
      endDate: 'Ngày kết thúc',
      indefinite: 'Không thời hạn',
      salary: 'Mức lương',
      salaryMode: 'Hình thức trả lương',
      workplace: 'Nơi làm việc',
      workingTime: 'Thời gian làm việc',
      otherBenefits: 'Chế độ khác',
      otherNotes: 'Lưu ý khác',
      note: 'Ghi chú',
      status: 'Trạng thái',
    },
    sign: {
      employee: 'Người lao động',
      employer: 'Người sử dụng lao động',
      hint: '(Ký, ghi rõ họ tên)',
    },
  },
} as const;
