/** Thống kê tài liệu */
export const documentStats = {
  title: 'Thống kê tài liệu',
  loading: 'Đang tải thống kê tài liệu...',
  filterType: 'Loại tài liệu',
  filterStatus: 'Trạng thái',
  filterCreator: 'Người tạo',
  kpiTotal: 'Tổng tài liệu',
  kpiActive: 'Hiệu lực',
  kpiDraft: 'Dự thảo',
  kpiPending: 'Chờ sửa',
  kpiObsolete: 'Lỗi thời',
  kpiTypes: 'Số loại',
  typeChart: 'Phân loại theo loại',
  statusChart: 'Phân loại theo trạng thái',
  trendChart: 'Xu hướng tạo theo tháng',
  creatorChart: 'Theo người tạo',
  quantity: 'Số lượng',
  typeTable: 'Theo loại tài liệu',
  typeCol: 'Loại tài liệu',
  totalCol: 'Tổng',
  draftCol: 'Dự thảo',
  activeCol: 'Hiệu lực',
  pendingCol: 'Chờ sửa',
  obsoleteCol: 'Lỗi thời',
  rateCol: 'Tỷ lệ hiệu lực',
  drillTitle: 'Chi tiết tài liệu',
  exportExcel: 'Xuất Excel',
  exportPdf: 'Xuất PDF',
  reportTitle: 'Báo cáo thống kê tài liệu',
  reportPeriod: 'Kỳ thống kê',
  reportTypeFilter: 'Lọc loại',
  reportStatusFilter: 'Lọc trạng thái',
  reportCreatorFilter: 'Lọc người tạo',
  reportExportDate: 'Ngày xuất',
  reportAllFilter: 'Tất cả',
  reportIndicator: 'Chỉ số',
  reportValue: 'Giá trị',
  reportRatio: 'Tỷ lệ',
  overviewSheet: 'Tổng quan',
  byTypeSheet: 'Theo loại',
  configureKpis: 'Tuỳ chỉnh KPI',
  emptyCharts: 'Chưa có dữ liệu để vẽ biểu đồ',
  exportError: 'Xuất báo cáo thất bại',
} as const;
