/** Người liên hệ */
export const contact = {
  title: 'Người liên hệ',
  deleteTitle: 'Xóa người liên hệ',
  deleteMessage: 'Bạn có chắc chắn muốn xóa người liên hệ này không?',
  bulkDeleteMessage: 'Bạn có chắc chắn muốn xóa {{count}} người liên hệ đã chọn?',
  noExportData: 'Không có dữ liệu để xuất',
  importTemplateName: 'Mau_Import_Nguoi_Lien_He',
  empty: 'Chưa có người liên hệ',
  emptyHint: 'Hãy thêm người liên hệ đầu tiên.',
  loading: 'Đang tải danh sách người liên hệ...',
  filterCustomer: 'Khách hàng',
  filterCreator: 'Người tạo',
  form: {
    editTitle: 'Chỉnh sửa người liên hệ',
    createTitle: 'Thêm người liên hệ',
    editSubtitle: 'Cập nhật thông tin người liên hệ',
    createSubtitle: 'Tạo người liên hệ mới',
    generalInfo: 'Thông tin chung',
    contactInfo: 'Liên hệ & ghi chú',
    customer: 'Khách hàng',
    customerPlaceholder: 'Chọn khách hàng',
    addNewOption: 'Thêm mới',
    name: 'Họ và tên',
    namePlaceholder: 'VD: Nguyễn Văn An',
    birthDate: 'Ngày sinh',
    birthYearOnly: 'Chỉ năm',
    birthFullDate: 'Ngày đầy đủ',
    birthYearPlaceholder: 'VD: 1990',
    title: 'Chức vụ',
    titlePlaceholder: 'VD: Giám đốc',
    phone: 'Số điện thoại',
    phonePlaceholder: 'VD: 0901234567',
    email: 'Email',
    emailPlaceholder: 'VD: ten@congty.vn',
    address: 'Địa chỉ',
    addressPlaceholder: 'Số nhà, đường, phường/xã, tỉnh/thành',
    note: 'Ghi chú',
    noteHint: 'Chỉ hiển thị nội bộ.',
  },
  store: {
    nameCol: 'Họ và tên',
    customerCol: 'Khách hàng',
    titleCol: 'Chức vụ',
    phoneCol: 'Số điện thoại',
    emailCol: 'Email',
    birthCol: 'Ngày sinh',
    addressCol: 'Địa chỉ',
    creatorCol: 'Người tạo',
    createdCol: 'Ngày tạo',
    updatedCol: 'Cập nhật cuối',
  },
  detail: {
    title: 'Chi tiết người liên hệ',
    subtitle: 'Hồ sơ người liên hệ',
    systemInfo: 'Thông tin hệ thống',
    createdAt: 'Được tạo lúc',
    updated: 'Cập nhật',
    sectionTitle: 'Người liên hệ',
    add: 'Thêm người liên hệ',
    empty: 'Chưa có người liên hệ',
  },
  validation: {
    customerRequired: 'Vui lòng chọn khách hàng',
    nameMin: 'Họ tên phải có ít nhất 2 ký tự',
    nameMax: 'Họ tên tối đa 200 ký tự',
    birthInvalid: 'Ngày sinh phải là năm (YYYY) hoặc ngày đầy đủ (YYYY-MM-DD)',
    titleMax: 'Chức vụ tối đa 100 ký tự',
    phoneInvalid: 'Số điện thoại không hợp lệ (bắt đầu 0, 10–11 chữ số)',
    emailInvalid: 'Email không hợp lệ',
    addressMax: 'Địa chỉ tối đa 500 ký tự',
    noteMax: 'Ghi chú tối đa 1000 ký tự',
  },
  toast: {
    createSuccess: 'Tạo người liên hệ thành công',
    updateSuccess: 'Cập nhật người liên hệ thành công',
    deleteSuccess: 'Đã xóa {{count}} người liên hệ',
    importSuccess: 'Đã nhập {{count}} người liên hệ',
  },
  export: {
    name: 'Họ và tên',
    customer: 'Khách hàng',
    customerCode: 'Mã khách hàng',
    birth: 'Ngày sinh',
    title: 'Chức vụ',
    phone: 'Số điện thoại',
    email: 'Email',
    address: 'Địa chỉ',
    note: 'Ghi chú',
  },
} as const;
