/** Thông tin công ty */
export const company = {
  "title": "Thông tin Doanh nghiệp",
  "description": "Thiết lập thông tin định danh và thương hiệu hiển thị trên hệ thống.",
  "brandSection": "Thương hiệu & Logo",
  "logoLabel": "Logo ứng dụng",
  "logoHint": "Hỗ trợ PNG, JPG, WebP. Tối đa 2MB.",
  "logoUrlLabel": "Dán link ảnh logo",
  "logoUrlPlaceholder": "https://…",
  "dropImage": "Thả ảnh vào đây",
  "upload": "Tải lên",
  "dragDrop": "Kéo thả",
  "capture": "Chụp",
  "imageHint": "Hỗ trợ PNG, JPG, WebP. Tối đa 2MB.",
  "appName": "Tên Ứng dụng",
  "appNamePlaceholder": "VD: VNPT",
  "appNameHint": "Hiển thị trên Sidebar và tiêu đề Browser.",
  "appDescription": "Mô tả ngắn",
  "appDescPlaceholder": "VD: Nền tảng quản trị nội bộ",
  "appDescHint": "Hiển thị dưới tên ứng dụng ở Sidebar.",
  "legalSection": "Thông tin pháp nhân",
  "companyName": "Tên Công ty đầy đủ",
  "companyNamePlaceholder": "VD: Công ty TNHH Thương mại ABC",
  "taxId": "Mã số thuế",
  "taxIdPlaceholder": "VD: 0123456789",
  "taxIdHint": "10 chữ số; chi nhánh thêm \"-\" và 3 số.",
  "phone": "Số điện thoại",
  "phonePlaceholder": "VD: 0281234567",
  "email": "Email liên hệ",
  "emailPlaceholder": "VD: lienhe@congty.vn",
  "website": "Website",
  "websitePlaceholder": "VD: https://congty.vn",
  "address": "Địa chỉ trụ sở",
  "addressPlaceholder": "Số nhà, đường, phường/xã, tỉnh/thành",
  "representative": "Người đại diện",
  "representativeHint": "Người ký hợp đồng lao động.",
  "representativeTitle": "Chức vụ người đại diện",
  "representativeTitlePlaceholder": "VD: Giám đốc",
  "signingPlace": "Địa điểm ký hợp đồng",
  "signingPlacePlaceholder": "VD: TP. Hồ Chí Minh",
  "signingPlaceHint": "Dùng làm mặc định trên hợp đồng lao động khi in.",
  "saveButton": "Lưu thông tin",
  "imageTypeError": "Vui lòng chỉ tải lên file hình ảnh.",
  "imageSizeError": "Kích thước ảnh không được vượt quá 2MB",
  "saveSuccess": "Cập nhật thông tin công ty thành công!",
  "validation": {
    "appNameMin": "Tên ứng dụng quá ngắn",
    "appDescMax": "Mô tả ngắn không được quá 30 ký tự",
    "companyNameMin": "Tên công ty là bắt buộc",
    "taxIdMin": "Mã số thuế không hợp lệ",
    "emailInvalid": "Email không hợp lệ",
    "logoUrlInvalid": "Logo phải là link ảnh hợp lệ (http/https) hoặc file đã tải lên"
  }
} as const;
