/** Thông báo nội bộ (Hành chính) */
export const announcement = {
  title: 'Thông báo',
  deleteTitle: 'Xóa thông báo',
  deleteMessage: 'Bạn có chắc chắn muốn xóa thông báo này không?',
  bulkDeleteMessage: 'Bạn có chắc chắn muốn xóa {{count}} thông báo đã chọn?',
  noExportData: 'Không có dữ liệu để xuất',
  empty: 'Chưa có thông báo',
  emptyHint: 'Hãy tạo thông báo nội bộ đầu tiên.',
  loading: 'Đang tải danh sách thông báo...',
  filterPosition: 'Chức vụ',
  filterCreator: 'Người tạo',
  filterAudience: 'Phạm vi',
  filterDateRange: 'Ngày đăng',
  allPositions: 'Tất cả chức vụ',
  audienceAll: 'Tất cả chức vụ',
  audienceByPosition: 'Theo chức vụ',
  form: {
    editTitle: 'Chỉnh sửa thông báo',
    createTitle: 'Thêm thông báo',
    editSubtitle: 'Cập nhật nội dung thông báo hiện có',
    createSubtitle: 'Tạo thông báo nội bộ mới',
    generalInfo: 'Nội dung thông báo',
    accessInfo: 'Phân quyền xem',
    datetime: 'Ngày giờ',
    title: 'Tiêu đề',
    content: 'Nội dung',
    positions: 'Chức vụ được xem',
    positionsPlaceholder: 'Chọn chức vụ được xem',
    positionsHint: 'Chọn chức vụ được phép xem. Để trống nếu gửi tới mọi người.',
  },
  store: {
    datetimeCol: 'Ngày giờ',
    titleCol: 'Tiêu đề',
    positionsCol: 'Chức vụ',
    creatorCol: 'Người tạo',
    updatedCol: 'Cập nhật cuối',
  },
  detail: {
    title: 'Chi tiết thông báo',
    subtitle: 'Thông báo nội bộ',
    generalInfo: 'Nội dung',
    accessInfo: 'Phân quyền xem',
    systemInfo: 'Thông tin hệ thống',
    createdAt: 'Được tạo lúc',
    updated: 'Cập nhật',
    changeAccess: 'Phân quyền',
    accessChangeTitle: 'Phân quyền xem',
    accessChangeHint:
      'Để trống chức vụ thì mọi người có quyền module đều xem được. Khi đã chọn, chỉ người tạo, quản trị viên và các chức vụ được chọn mới thấy thông báo.',
    accessEveryone: 'Công khai trong module (không giới hạn chức vụ)',
    accessRestricted: 'Đã giới hạn theo chức vụ',
    selectedPositionsCount: 'Đã chọn {{count}} chức vụ',
    unassignedDept: 'Chưa gán phòng ban',
  },
  validation: {
    datetimeRequired: 'Vui lòng chọn ngày giờ',
    titleRequired: 'Vui lòng nhập tiêu đề',
    titleMax: 'Tiêu đề tối đa 200 ký tự',
    contentRequired: 'Vui lòng nhập nội dung',
    contentMax: 'Nội dung tối đa 10.000 ký tự',
  },
  toast: {
    createSuccess: 'Đã tạo thông báo',
    updateSuccess: 'Đã cập nhật thông báo',
    deleteSuccess: 'Đã xóa {{count}} thông báo',
  },
  export: {
    datetime: 'Ngày giờ',
    title: 'Tiêu đề',
    content: 'Nội dung',
    positions: 'Chức vụ',
    creator: 'Người tạo',
  },
};
