/** Thiết lập tài liệu — loại tài liệu (+ tab sau) */
export const documentSettings = {
  title: 'Thiết lập tài liệu',
  tabDocumentType: 'Loại tài liệu',
  filterCreator: 'Người tạo',
  loai: {
    title: 'Loại tài liệu',
    deleteTitle: 'Xóa loại tài liệu',
    deleteMessage: 'Bạn có chắc chắn muốn xóa loại tài liệu này không?',
    bulkDeleteMessage: 'Bạn có chắc chắn muốn xóa {{count}} loại tài liệu đã chọn?',
    noExportData: 'Không có dữ liệu để xuất',
    importTemplateName: 'Mau_Import_Loai_Tai_Lieu',
    empty: 'Chưa có loại tài liệu',
    emptyHint: 'Hãy tạo loại tài liệu đầu tiên để phân loại kho tài liệu.',
    loading: 'Đang tải danh sách loại tài liệu...',
    form: {
      editTitle: 'Chỉnh sửa loại tài liệu',
      createTitle: 'Thêm loại tài liệu',
      editSubtitle: 'Cập nhật thông tin loại tài liệu hiện có',
      createSubtitle: 'Thiết lập loại tài liệu mới',
      generalInfo: 'Thông tin chung',
      order: 'Thứ tự',
      name: 'Tên loại tài liệu',
      namePlaceholder: 'VD: Hợp đồng, Biên bản…',
      description: 'Mô tả',
    },
    store: {
      orderCol: 'Thứ tự',
      nameCol: 'Tên loại',
      descCol: 'Mô tả',
      creatorCol: 'Người tạo',
      createdCol: 'Ngày tạo',
      updatedCol: 'Cập nhật cuối',
    },
    detail: {
      title: 'Chi tiết loại tài liệu',
      subtitle: 'Loại tài liệu',
      systemInfo: 'Thông tin hệ thống',
      createdAt: 'Được tạo lúc',
      updated: 'Cập nhật',
    },
    validation: {
      nameMin: 'Tên loại tài liệu phải có ít nhất 2 ký tự',
      nameMax: 'Tên loại tài liệu tối đa 100 ký tự',
      descMax: 'Mô tả tối đa 500 ký tự',
      orderMin: 'Thứ tự phải là số nguyên ≥ 0',
    },
    toast: {
      createSuccess: 'Tạo loại tài liệu thành công',
      updateSuccess: 'Cập nhật loại tài liệu thành công',
      deleteSuccess: 'Đã xóa {{count}} loại tài liệu',
      importSuccess: 'Đã nhập {{count}} loại tài liệu',
    },
    exportOrder: 'Thứ tự',
    exportName: 'Tên loại tài liệu',
    exportDesc: 'Mô tả',
  },
} as const;
