/** Thống kê phiếu hành chính */
export const adminFormStats = {
  title: 'Thống kê phiếu hành chính',
  loading: 'Đang tải thống kê phiếu hành chính...',
  filterType: 'Loại phiếu',
  filterStatus: 'Trạng thái',
  filterDepartment: 'Phòng ban',
  filterEmployee: 'Nhân viên',
  kpiTotal: 'Tổng phiếu',
  kpiApproved: 'Đã duyệt',
  kpiPending: 'Chờ duyệt',
  kpiRejected: 'Từ chối',
  kpiDays: 'Tổng ngày (đã duyệt)',
  kpiTypes: 'Số loại',
  typeChart: 'Phân loại theo loại phiếu',
  statusChart: 'Phân loại theo trạng thái',
  trendChart: 'Xu hướng theo tháng (từ ngày)',
  departmentChart: 'Theo phòng ban',
  quantity: 'Số lượng',
  typeTable: 'Theo loại phiếu',
  typeCol: 'Loại phiếu',
  totalCol: 'Tổng',
  approvedCol: 'Đã duyệt',
  pendingCol: 'Chờ duyệt',
  rejectedCol: 'Từ chối',
  daysCol: 'Tổng ngày',
  avgDaysCol: 'TB ngày',
  drillTitle: 'Chi tiết phiếu',
  exportExcel: 'Xuất Excel',
  exportPdf: 'Xuất PDF',
  reportTitle: 'Báo cáo thống kê phiếu hành chính',
  reportPeriod: 'Kỳ thống kê',
  reportTypeFilter: 'Lọc loại',
  reportStatusFilter: 'Lọc trạng thái',
  reportDeptFilter: 'Lọc phòng ban',
  reportEmployeeFilter: 'Lọc nhân viên',
  reportExportDate: 'Ngày xuất',
  reportAllFilter: 'Tất cả',
  reportIndicator: 'Chỉ số',
  reportValue: 'Giá trị',
  reportRatio: 'Tỷ lệ',
  overviewSheet: 'Tổng quan',
  byTypeSheet: 'Theo loại',
  configureKpis: 'Tuỳ chỉnh KPI',
  emptyCharts: 'Chưa có dữ liệu để vẽ biểu đồ',
  exportError: 'Xuất báo cáo thất bại',
} as const;
