/** Phòng ban */
export const department = {
  "exportCode": "Mã phòng ban",
  "exportName": "Tên phòng ban",
  "exportLevel": "Cấp độ",
  "exportOrder": "Thứ tự",
  "exportStatus": "Trạng thái",
  "exportSuccess": "Xuất file thành công",
  "noExportData": "Không có dữ liệu để xuất",
  "importDeveloping": "Chức năng Import đang phát triển",
  "toolbar": {
    "department": "Phòng"
  },
  "footerRecords": "bản ghi",
  "title": "Phòng ban",
  "pageTitle": "Cơ cấu tổ chức",
  "pageDescription": "Quản lý sơ đồ phòng ban và phân cấp đơn vị. Tối đa 2 cấp: phòng ban gốc và nhóm trực thuộc.",
  "addButton": "Thêm phòng ban",
  "searchPlaceholder": "Tìm theo tên hoặc mã phòng ban",
  "totalCount": "Tổng số: {{count}} đơn vị",
  "deleteTitle": "Xóa phòng ban",
  "deleteMessage": "Bạn có chắc chắn muốn xóa phòng ban này? Không thể xóa nếu còn phòng con. Chức vụ thuộc phòng này sẽ chuyển sang Chưa phân bổ.",
  "loading": "Đang tải cấu trúc phòng ban...",
  "empty": "Chưa có phòng ban nào",
  "emptyHint": "Hãy tạo phòng ban đầu tiên để thiết lập cơ cấu tổ chức.",
  "name": "Tên phòng ban",
  "code": "Mã số",
  "level": "Cấp độ",
  "levelBadge": "Level {{level}}",
  "active": "Hoạt động",
  "inactive": "Ngừng",
  "form": {
    "editTitle": "Chỉnh sửa phòng ban",
    "createTitle": "Thêm phòng ban mới",
    "code": "Mã phòng ban",
    "codePlaceholder": "VD: IT_DEV",
    "codeHint": "Chỉ chữ in hoa, số và dấu gạch dưới (_).",
    "name": "Tên phòng ban",
    "namePlaceholder": "VD: Phòng Phát triển Phần mềm",
    "parent": "Thuộc phòng ban",
    "parentNone": "— Phòng ban gốc —",
    "parentHint": "Để trống nếu là phòng ban độc lập (cấp 1). Chỉ chọn khi tạo nhóm/bộ phận (cấp 2).",
    "parentLockedHasChildren": "Không thể đổi phòng cha vì đơn vị này đang có nhóm con.",
    "sortOrder": "Thứ tự hiển thị",
    "status": "Trạng thái",
    "statusActive": "Đang hoạt động",
    "statusInactive": "Ngừng hoạt động",
    "description": "Mô tả"
  },
  "validation": {
    "codeMin": "Mã phòng ban phải có ít nhất 2 ký tự",
    "codeMax": "Mã phòng ban tối đa 50 ký tự",
    "codeFormat": "Mã chỉ chứa chữ hoa, số và gạch dưới (VD: IT_DEV)",
    "nameMin": "Tên phòng ban phải có ít nhất 3 ký tự",
    "nameMax": "Tên phòng ban quá dài",
    "statusInvalid": "Trạng thái không hợp lệ",
    "sortOrderMin": "Thứ tự phải lớn hơn hoặc bằng 0",
    "parentMustBeRoot": "Chỉ được chọn phòng ban gốc (cấp 1) làm phòng cha.",
    "maxDepthExceeded": "Cơ cấu tối đa 2 cấp. Không thể tạo thêm cấp con.",
    "cannotMoveParentWithChildren": "Không thể đổi phòng cha vì đơn vị này đang có nhóm con."
  },
  "toast": {
    "createSuccess": "Tạo phòng ban thành công",
    "updateSuccess": "Cập nhật thành công",
    "deleteSuccess": "Xóa phòng ban thành công",
    "importSuccess": "Đã import {{count}} phòng ban",
    "statusUpdate": "Đã đổi trạng thái {{count}} phòng ban",
    "deleteSkipped": "Bỏ qua {{count}} phòng ban còn phòng con"
  },
  "importTemplateName": "Mau_Import_Phong_Ban",
  "service": {
    "notFound": "Phòng ban không tồn tại",
    "hasChildren": "Không thể xóa phòng ban đang chứa phòng ban con.",
    "parentMustBeRoot": "Chỉ được chọn phòng ban gốc (cấp 1) làm phòng cha.",
    "maxDepthExceeded": "Cơ cấu tối đa 2 cấp. Không thể tạo thêm cấp con.",
    "cannotMoveParentWithChildren": "Không thể đổi phòng cha vì đơn vị này đang có nhóm con."
  },
  "detail": {
    "title": "Chi tiết phòng ban",
    "activate": "Kích hoạt",
    "deactivate": "Ngưng",
    "level": "Cấp độ",
    "order": "Thứ tự",
    "parent": "Thuộc phòng ban",
    "noParent": "— Phòng ban gốc —",
    "updated": "Cập nhật",
    "createdAt": "Được tạo lúc",
    "basicInfo": "Thông tin cơ bản",
    "systemInfo": "Thông tin hệ thống",
    "description": "Mô tả",
    "childrenSection": "Nhóm / bộ phận trực thuộc",
    "addChild": "Thêm",
    "noChildren": "Chưa có phòng ban con",
    "noChildrenHint": "Dùng nút Thêm ở góc phải để tạo đơn vị cấp dưới trực tiếp.",
    "positionsSection": "Chức vụ",
    "addPosition": "Thêm",
    "noPositions": "Chưa có chức vụ",
    "noPositionsHint": "Dùng nút Thêm ở góc phải để tạo chức vụ trong phòng ban này."
  },
  "store": {
    "orderCol": "Thứ tự",
    "nameCol": "Tên phòng ban",
    "codeCol": "Mã số",
    "descCol": "Mô tả",
    "levelCol": "Cấp độ",
    "statusCol": "Trạng thái",
    "parentCol": "Trực thuộc",
    "updatedCol": "Cập nhật"
  },
  "statusChangeTitle": "Chuyển trạng thái phòng ban",
  "statusChangeMessage": "Chuyển \"{{name}}\" sang trạng thái {{status}}?"
} as const;
