import type { LucideIcon } from 'lucide-react';
import {
  Ban,
  Building2,
  Calendar,
  CircleDot,
  Clock,
  FileText,
  ImageIcon,
  MessageSquare,
  ShieldCheck,
  StickyNote,
  Sun,
  User,
  UserCheck,
} from 'lucide-react';

export const PHIEU_HANH_CHINH_FIELD_ICONS = {
  ma_phieu: FileText,
  ten_loai_phieu: FileText,
  id_nhan_vien: User,
  ten_phong_ban: Building2,
  id_phong_ban: Building2,
  trang_thai: CircleDot,
  ly_do: MessageSquare,
  tu_ngay: Calendar,
  buoi_bat_dau: Sun,
  den_ngay: Calendar,
  buoi_ket_thuc: Sun,
  gio_bat_dau: Clock,
  gio_ket_thuc: Clock,
  hinh_anh: ImageIcon,
  id_ql_duyet: UserCheck,
  ten_ql_duyet: UserCheck,
  tg_ql_duyet: Calendar,
  ghi_chu_ql: StickyNote,
  id_hcns_duyet: ShieldCheck,
  ten_hcns_duyet: ShieldCheck,
  tg_hcns_duyet: Calendar,
  ghi_chu_hcns: StickyNote,
  ly_do_tu_choi: Ban,
} as const satisfies Record<string, LucideIcon>;
