/** Danh sách khách hàng */
export const customer = {
  title: 'Danh sách khách hàng',
  deleteTitle: 'Xóa khách hàng',
  deleteMessage: 'Bạn có chắc chắn muốn xóa khách hàng này không?',
  bulkDeleteMessage: 'Bạn có chắc chắn muốn xóa {{count}} khách hàng đã chọn?',
  noExportData: 'Không có dữ liệu để xuất',
  importTemplateName: 'Mau_Import_Khach_Hang',
  empty: 'Chưa có khách hàng',
  emptyHint: 'Hãy thêm khách hàng đầu tiên để bắt đầu quản lý.',
  loading: 'Đang tải danh sách khách hàng...',
  filterGroup: 'Nhóm KH',
  filterStatus: 'Trạng thái',
  filterCreator: 'Người tạo',
  form: {
    editTitle: 'Chỉnh sửa khách hàng',
    createTitle: 'Thêm khách hàng',
    editSubtitle: 'Cập nhật thông tin khách hàng hiện có',
    createSubtitle: 'Tạo hồ sơ khách hàng mới',
    generalInfo: 'Thông tin chung',
    contactInfo: 'Liên hệ & ghi chú',
    code: 'Mã khách hàng',
    codePlaceholder: 'VD: KH0001',
    name: 'Tên khách hàng',
    namePlaceholder: 'VD: Công ty TNHH Minh Phát',
    phone: 'Số điện thoại',
    phonePlaceholder: 'VD: 0901234567',
    address: 'Địa chỉ',
    addressPlaceholder: 'Số nhà, đường, phường/xã, tỉnh/thành',
    note: 'Ghi chú',
    noteHint: 'Chỉ hiển thị nội bộ.',
    group: 'Nhóm khách hàng',
    groupPlaceholder: 'Chọn nhóm khách hàng',
    status: 'Trạng thái',
    statusPlaceholder: 'Chọn trạng thái khách hàng',
    addNewOption: 'Thêm mới',
  },
  store: {
    codeCol: 'Mã KH',
    nameCol: 'Tên khách hàng',
    phoneCol: 'Số điện thoại',
    addressCol: 'Địa chỉ',
    noteCol: 'Ghi chú',
    groupCol: 'Nhóm',
    statusCol: 'Trạng thái',
    contactCol: 'Người liên hệ',
    creatorCol: 'Người tạo',
    createdCol: 'Ngày tạo',
    updatedCol: 'Cập nhật cuối',
  },
  detail: {
    title: 'Chi tiết khách hàng',
    subtitle: 'Hồ sơ khách hàng',
    systemInfo: 'Thông tin hệ thống',
    createdAt: 'Được tạo lúc',
    updated: 'Cập nhật',
    changeStatus: 'Trạng thái',
    changeGroup: 'Nhóm khách hàng',
    statusChangeTitle: 'Đổi trạng thái',
    statusChangeMessage: 'Chọn trạng thái mới cho',
    groupChangeTitle: 'Đổi nhóm khách hàng',
    groupChangeMessage: 'Chọn nhóm mới cho',
  },
  validation: {
    codeRequired: 'Mã khách hàng là bắt buộc',
    codeMax: 'Mã khách hàng tối đa 50 ký tự',
    nameMin: 'Tên khách hàng phải có ít nhất 2 ký tự',
    nameMax: 'Tên khách hàng tối đa 200 ký tự',
    phoneInvalid: 'Số điện thoại không hợp lệ (bắt đầu 0, 10–11 chữ số)',
    addressMax: 'Địa chỉ tối đa 500 ký tự',
    noteMax: 'Ghi chú tối đa 1000 ký tự',
    groupRequired: 'Vui lòng chọn nhóm khách hàng',
    statusRequired: 'Vui lòng chọn trạng thái',
  },
  toast: {
    createSuccess: 'Tạo khách hàng thành công',
    updateSuccess: 'Cập nhật khách hàng thành công',
    deleteSuccess: 'Đã xóa {{count}} khách hàng',
    importSuccess: 'Đã nhập {{count}} khách hàng',
    duplicateContactsSuccess: 'Đã sao chép {{count}} người liên hệ',
    duplicateContactsError: 'Không sao chép được người liên hệ. Vui lòng thêm thủ công.',
  },
  export: {
    code: 'Mã khách hàng',
    name: 'Tên khách hàng',
    phone: 'Số điện thoại',
    address: 'Địa chỉ',
    note: 'Ghi chú',
    group: 'Nhóm khách hàng',
    status: 'Trạng thái',
  },
} as const;
