import type { LucideIcon } from 'lucide-react';
import {
  AtSign,
  Briefcase,
  Building2,
  Camera,
  CircleDot,
  CreditCard,
  GraduationCap,
  Heart,
  IdCard,
  KeyRound,
  Landmark,
  Layers,
  Mail,
  MapPin,
  Phone,
  School,
  Shield,
  ShieldCheck,
  User,
  UserCircle,
  Users,
} from 'lucide-react';

export const EMPLOYEE_FIELD_ICONS = {
  anh_dai_dien: Camera,
  ho_ten: UserCircle,
  gioi_tinh: Users,
  ngay_sinh: User,
  tinh_trang_hon_nhan: Heart,
  quoc_tich: MapPin,
  dan_toc: User,
  ton_giao: User,
  que_quan: MapPin,
  so_cccd: IdCard,
  ngay_cap_cccd: IdCard,
  noi_cap_cccd: IdCard,
  dia_chi_thuong_tru: MapPin,
  dia_chi_hien_tai: MapPin,
  email: Mail,
  email_ca_nhan: Mail,
  so_dien_thoai: Phone,
  nguoi_lien_he_khan: User,
  sdt_khan: Phone,
  moi_quan_he: Heart,
  chuc_vu_id: Briefcase,
  phong_ban_id: Building2,
  ten_bo_phan: Building2,
  cap_bac: Layers,
  trang_thai: CircleDot,
  ngay_vao_lam: Briefcase,
  ngay_chinh_thuc: Briefcase,
  ngay_nghi_viec: Briefcase,
  ly_do_nghi: CircleDot,
  trinh_do: GraduationCap,
  chuyen_nganh: Briefcase,
  truong: School,
  so_tai_khoan: CreditCard,
  ten_chu_tai_khoan: User,
  ngan_hang: Landmark,
  chi_nhanh: Building2,
  so_so_bhxh: Shield,
  so_bhyt: ShieldCheck,
  ma_so_thue_ca_nhan: IdCard,
  ten_dang_nhap: AtSign,
  mat_khau_tam: KeyRound,
  tai_khoan_dang_hoat_dong: ShieldCheck,
} as const satisfies Record<string, LucideIcon>;
