/** Phiếu hành chính */
export const adminForm = {
  title: 'Phiếu hành chính',
  deleteTitle: 'Xóa phiếu hành chính',
  deleteMessage: 'Bạn có chắc chắn muốn xóa phiếu này không?',
  bulkDeleteMessage: 'Bạn có chắc chắn muốn xóa {{count}} phiếu đã chọn?',
  noExportData: 'Không có dữ liệu để xuất',
  importTemplateName: 'Mau_Import_Phieu_Hanh_Chinh',
  empty: 'Chưa có phiếu hành chính',
  emptyHint: 'Hãy tạo phiếu đầu tiên để bắt đầu quản lý.',
  loading: 'Đang tải danh sách phiếu hành chính...',
  filterType: 'Loại phiếu',
  filterStatus: 'Trạng thái',
  filterEmployee: 'Nhân viên',
  filterDepartment: 'Phòng ban',
  filterCreator: 'Người tạo',
  filterDateRange: 'Thời gian',
  approveQlTitle: 'Duyệt cấp quản lý',
  approveQlMessage: 'Xác nhận duyệt phiếu này? Phiếu sẽ chuyển sang chờ HCNS duyệt.',
  approveHcnsTitle: 'Duyệt cấp HCNS',
  approveHcnsMessage: 'Xác nhận duyệt phiếu này? Phiếu sẽ được đánh dấu Đã duyệt.',
  rejectTitle: 'Từ chối phiếu',
  rejectMessage: 'Từ chối phiếu này? Vui lòng nhập lý do từ chối ở bước tiếp theo.',
  cancelTitle: 'Hủy phiếu',
  cancelMessage: 'Bạn muốn hủy phiếu này? Chỉ hủy được khi còn chờ QL duyệt. Phiếu sẽ chuyển sang trạng thái Đã hủy.',
  approveQlAction: 'Duyệt QL',
  approveHcnsAction: 'Duyệt HCNS',
  rejectAction: 'Từ chối',
  cancelAction: 'Hủy phiếu',
  rejectReasonPrompt: 'Nhập lý do từ chối',
  rejectReasonRequired: 'Vui lòng nhập lý do từ chối',
  form: {
    editTitle: 'Chỉnh sửa phiếu',
    createTitle: 'Tạo phiếu hành chính',
    editSubtitle: 'Cập nhật thông tin phiếu đang chờ QL duyệt',
    createSubtitle: 'Tạo phiếu hành chính mới',
    generalInfo: 'Thông tin phiếu',
    timeInfo: 'Thời gian',
    attachmentInfo: 'Hình ảnh đính kèm',
    type: 'Loại phiếu',
    typePlaceholder: 'Chọn loại phiếu',
    employee: 'Nhân viên',
    employeePlaceholder: 'Chọn nhân viên',
    fromDate: 'Từ ngày',
    toDate: 'Đến ngày',
    startShift: 'Buổi bắt đầu',
    endShift: 'Buổi kết thúc',
    startTime: 'Giờ bắt đầu',
    endTime: 'Giờ kết thúc',
    reason: 'Lý do',
    reasonPlaceholder: 'VD: Về quê giải quyết việc gia đình',
    images: 'Hình ảnh',
  },
  store: {
    typeCol: 'Loại phiếu',
    employeeCol: 'Nhân viên',
    fromCol: 'Từ ngày',
    toCol: 'Đến ngày',
    statusCol: 'Trạng thái',
    reasonCol: 'Lý do',
    startShiftCol: 'Buổi bắt đầu',
    endShiftCol: 'Buổi kết thúc',
    creatorCol: 'Người tạo',
    createdCol: 'Ngày tạo',
    updatedCol: 'Cập nhật cuối',
    codeCol: 'Mã phiếu',
  },
  detail: {
    title: 'Chi tiết phiếu hành chính',
    subtitle: 'Hồ sơ phiếu hành chính',
    approvalInfo: 'Thông tin duyệt',
    status: 'Trạng thái',
    qlApprover: 'Người duyệt QL',
    qlApprovedAt: 'Tg duyệt QL',
    qlNote: 'Ghi chú QL',
    hcnsApprover: 'Người duyệt HCNS',
    hcnsApprovedAt: 'Tg duyệt HCNS',
    hcnsNote: 'Ghi chú HCNS',
    rejectReason: 'Lý do từ chối',
    systemInfo: 'Thông tin hệ thống',
    createdAt: 'Được tạo lúc',
    updated: 'Cập nhật',
    images: 'Hình ảnh',
  },
  validation: {
    typeRequired: 'Vui lòng chọn loại phiếu',
    employeeRequired: 'Vui lòng chọn nhân viên',
    fromDateRequired: 'Vui lòng chọn từ ngày',
    toDateRequired: 'Vui lòng chọn đến ngày',
    shiftRequired: 'Vui lòng chọn buổi',
    reasonMax: 'Lý do tối đa 2000 ký tự',
    timeInvalid: 'Giờ không hợp lệ (HH:mm)',
  },
  toast: {
    createSuccess: 'Tạo phiếu thành công',
    updateSuccess: 'Cập nhật phiếu thành công',
    deleteSuccess: 'Đã xóa {{count}} phiếu',
    importSuccess: 'Đã nhập {{count}} phiếu',
    approveQlSuccess: 'Đã duyệt cấp quản lý',
    approveHcnsSuccess: 'Đã duyệt cấp HCNS',
    rejectSuccess: 'Đã từ chối phiếu',
    cancelSuccess: 'Đã hủy phiếu',
  },
  export: {
    type: 'Loại phiếu',
    typeCode: 'Mã loại',
    employee: 'Nhân viên',
    department: 'Phòng ban',
    fromDate: 'Từ ngày',
    startShift: 'Buổi bắt đầu',
    toDate: 'Đến ngày',
    endShift: 'Buổi kết thúc',
    startTime: 'Giờ bắt đầu',
    endTime: 'Giờ kết thúc',
    reason: 'Lý do',
    status: 'Trạng thái',
  },
} as const;
