/** Danh sách market in */
export const printMarket = {
  title: 'Danh sách market in',
  deleteTitle: 'Xóa market in',
  deleteMessage: 'Bạn có chắc chắn muốn xóa market in này không?',
  bulkDeleteMessage: 'Bạn có chắc chắn muốn xóa {{count}} market in đã chọn?',
  noExportData: 'Không có dữ liệu để xuất',
  importTemplateName: 'Mau_Import_Market_In',
  empty: 'Chưa có market in',
  emptyHint: 'Hãy thêm market in đầu tiên để bắt đầu quản lý.',
  loading: 'Đang tải danh sách market in...',
  filterCustomer: 'Khách hàng',
  filterStatus: 'Trạng thái',
  filterArtist: 'Người vẽ',
  filterCreator: 'Người tạo',
  approveTitle: 'Duyệt market in',
  approveMessage: 'Duyệt market in này? Hệ thống sẽ ghi nhận người duyệt và thời gian duyệt.',
  suspendTitle: 'Ngừng áp dụng',
  suspendMessage: 'Chuyển market in sang trạng thái Ngừng áp dụng?',
  approveAction: 'Duyệt',
  suspendAction: 'Ngừng áp dụng',
  reapplyAction: 'Áp dụng lại',
  reapplyTitle: 'Áp dụng lại market in',
  reapplyMessage:
    'Chuyển market in về trạng thái Đã duyệt? Hệ thống sẽ cập nhật người duyệt và thời gian duyệt.',
  form: {
    editTitle: 'Chỉnh sửa market in',
    createTitle: 'Thêm market in',
    editSubtitle: 'Cập nhật thông tin market in hiện có',
    createSubtitle: 'Tạo bản ghi market in mới',
    generalInfo: 'Thông tin chung',
    fileInfo: 'File & hiệu lực',
    order: 'Thứ tự',
    customer: 'Khách hàng',
    customerPlaceholder: 'Chọn khách hàng',
    productCode: 'Mã sản phẩm',
    productCodePlaceholder: 'VD: SP-BAG-001',
    marketCode: 'Mã market',
    marketCodePlaceholder: 'VD: MI0001',
    description: 'Mô tả',
    linkFile: 'Link file',
    linkFilePlaceholder: 'https://…',
    artist: 'Người vẽ',
    artistPlaceholder: 'Chọn người vẽ',
    effectiveDate: 'Ngày hiệu lực',
  },
  store: {
    orderCol: 'Thứ tự',
    marketCodeCol: 'Mã market',
    productCodeCol: 'Mã SP',
    customerCol: 'Khách hàng',
    customerCodeCol: 'Mã KH',
    statusCol: 'Trạng thái',
    artistCol: 'Người vẽ',
    effectiveCol: 'Hiệu lực',
    linkCol: 'Link file',
    descCol: 'Mô tả',
    approverCol: 'Người duyệt',
    approvedAtCol: 'Tg duyệt',
    creatorCol: 'Người tạo',
    createdCol: 'Ngày tạo',
    updatedCol: 'Cập nhật cuối',
  },
  detail: {
    title: 'Chi tiết market in',
    subtitle: 'Hồ sơ market in',
    approvalInfo: 'Thông tin duyệt',
    status: 'Trạng thái',
    approver: 'Người duyệt',
    approvedAt: 'Thời gian duyệt',
    systemInfo: 'Thông tin hệ thống',
    createdAt: 'Được tạo lúc',
    updated: 'Cập nhật',
  },
  status: {
    cho_duyet: 'Chờ duyệt',
    da_duyet: 'Đã duyệt',
    ngung_ap_dung: 'Ngừng áp dụng',
  },
  validation: {
    orderInvalid: 'Thứ tự phải là số nguyên',
    orderMin: 'Thứ tự phải ≥ 0',
    customerRequired: 'Vui lòng chọn khách hàng',
    productCodeRequired: 'Mã sản phẩm là bắt buộc',
    productCodeMax: 'Mã sản phẩm tối đa 100 ký tự',
    marketCodeRequired: 'Mã market là bắt buộc',
    marketCodeMax: 'Mã market tối đa 50 ký tự',
    descMax: 'Mô tả tối đa 1000 ký tự',
    linkInvalid: 'Link file không hợp lệ (cần URL đầy đủ)',
  },
  toast: {
    createSuccess: 'Tạo market in thành công',
    updateSuccess: 'Cập nhật market in thành công',
    deleteSuccess: 'Đã xóa {{count}} market in',
    importSuccess: 'Đã nhập {{count}} market in',
    approveSuccess: 'Đã duyệt market in',
    reapplySuccess: 'Đã áp dụng lại market in',
    suspendSuccess: 'Đã ngừng áp dụng market in',
  },
  export: {
    order: 'Thứ tự',
    marketCode: 'Mã market',
    productCode: 'Mã sản phẩm',
    customerCode: 'Mã khách hàng',
    customerName: 'Tên khách hàng',
    description: 'Mô tả',
    linkFile: 'Link file',
    artist: 'Người vẽ',
    status: 'Trạng thái',
    effectiveDate: 'Ngày hiệu lực',
  },
} as const;
