/** Danh sách tài liệu */
export const document = {
  title: 'Danh sách tài liệu',
  deleteTitle: 'Xóa tài liệu',
  deleteMessage: 'Bạn có chắc chắn muốn xóa tài liệu này không?',
  bulkDeleteMessage: 'Bạn có chắc chắn muốn xóa {{count}} tài liệu đã chọn?',
  noExportData: 'Không có dữ liệu để xuất',
  importTemplateName: 'Mau_Import_Danh_Sach_Tai_Lieu',
  empty: 'Chưa có tài liệu',
  emptyHint: 'Hãy thêm tài liệu đầu tiên vào kho.',
  loading: 'Đang tải danh sách tài liệu...',
  filterType: 'Loại tài liệu',
  filterStatus: 'Trạng thái',
  filterCreator: 'Người tạo',
  form: {
    editTitle: 'Chỉnh sửa tài liệu',
    createTitle: 'Thêm tài liệu',
    editSubtitle: 'Cập nhật thông tin tài liệu hiện có',
    createSubtitle: 'Thêm tài liệu mới vào kho',
    generalInfo: 'Thông tin chung',
    accessInfo: 'Phân quyền xem',
    type: 'Loại tài liệu',
    typePlaceholder: 'Chọn loại tài liệu',
    name: 'Tên tài liệu',
    namePlaceholder: 'VD: Mẫu hợp đồng lao động',
    description: 'Mô tả',
    link: 'Link tài liệu',
    linkPlaceholder: 'https://…',
    note: 'Ghi chú',
    noteHint: 'Chỉ hiển thị nội bộ.',
    status: 'Trạng thái',
    positions: 'Phân quyền chức vụ',
    positionsPlaceholder: 'Chọn chức vụ được xem',
    employees: 'Phân quyền nhân viên',
    employeesPlaceholder: 'Chọn nhân viên được xem',
  },
  store: {
    nameCol: 'Tên tài liệu',
    typeCol: 'Loại',
    statusCol: 'Trạng thái',
    linkCol: 'Link',
    descCol: 'Mô tả',
    creatorCol: 'Người tạo',
    createdCol: 'Ngày tạo',
    updatedCol: 'Cập nhật cuối',
  },
  detail: {
    title: 'Chi tiết tài liệu',
    subtitle: 'Hồ sơ tài liệu',
    accessInfo: 'Phân quyền xem',
    positions: 'Chức vụ được xem',
    employees: 'Nhân viên được xem',
    systemInfo: 'Thông tin hệ thống',
    createdAt: 'Được tạo lúc',
    updated: 'Cập nhật',
    changeStatus: 'Trạng thái',
    changeAccess: 'Phân quyền',
    statusChangeTitle: 'Đổi trạng thái',
    statusChangeMessage: 'Chọn trạng thái mới cho',
    accessChangeTitle: 'Phân quyền xem',
    accessChangeHint:
      'Để trống cả chức vụ và nhân viên thì mọi người có quyền module đều xem được. Khi đã chọn, chỉ người tạo, quản trị viên và các đối tượng được chọn mới thấy tài liệu.',
    accessEveryone: 'Công khai trong module (không giới hạn chức vụ / nhân viên)',
    accessRestricted: 'Đã giới hạn theo chức vụ hoặc nhân viên',
    selectedPositionsCount: 'Đã chọn {{count}} chức vụ',
    selectedEmployeesCount: 'Đã chọn {{count}} nhân viên',
    unassignedDept: 'Chưa gán phòng ban',
  },
  validation: {
    typeRequired: 'Vui lòng chọn loại tài liệu',
    nameMin: 'Tên tài liệu phải có ít nhất 2 ký tự',
    nameMax: 'Tên tài liệu tối đa 200 ký tự',
    descMax: 'Mô tả tối đa 1000 ký tự',
    noteMax: 'Ghi chú tối đa 1000 ký tự',
    linkInvalid: 'Link tài liệu không hợp lệ (cần URL đầy đủ)',
  },
  toast: {
    createSuccess: 'Tạo tài liệu thành công',
    updateSuccess: 'Cập nhật tài liệu thành công',
    deleteSuccess: 'Đã xóa {{count}} tài liệu',
    importSuccess: 'Đã nhập {{count}} tài liệu',
  },
  export: {
    type: 'Loại tài liệu',
    name: 'Tên tài liệu',
    description: 'Mô tả',
    link: 'Link',
    note: 'Ghi chú',
    status: 'Trạng thái',
  },
} as const;
