/** Phân quyền */
export const permission = {
  "title": "Phân quyền",
  "tabModule": "Phân quyền Module",
  "tabLog": "Nhật ký hệ thống",
  "exportReport": "Xuất báo cáo",
  "active": "Hoạt động",
  "inactive": "Ngừng",
  "staffCount": "{{count}} nhân sự",
  "log": {
    "success": "Thành công",
    "warning": "Cảnh báo",
    "error": "Lỗi",
    "systemTime": "Thời gian hệ thống",
    "action": "Hành động"
  },
  "form": {
    "editTitle": "Cấu hình quyền hạn",
    "createTitle": "Phân quyền Chức vụ",
    "subtitle": "Quản lý các quyền thao tác dựa trên đặc thù từng module.",
    "update": "Cập nhật phân quyền",
    "create": "Thiết lập ngay",
    "infoSection": "Thông tin Chức vụ",
    "codeLabel": "Mã định danh",
    "codePlaceholder": "VD: TP_KETOAN",
    "nameLabel": "Tên hiển thị",
    "namePlaceholder": "VD: Trưởng phòng Kế toán",
    "matrixTitle": "Ma trận Phân quyền Nghiệp vụ",
    "matrixHint": "Các ô - biểu thị hành động không khả dụng cho module đó.",
    "legendAction": "Thao tác",
    "legendApproval": "Phê duyệt",
    "moduleHeader": "Module Hệ thống",
    "view": "Xem",
    "add": "Thêm",
    "edit": "Sửa",
    "delete": "Xóa",
    "approve": "Duyệt",
    "export": "Xuất",
    "import": "Nhập",
    "all": "Toàn bộ"
  },
  "matrix": {
    "loading": "Đang tải dữ liệu...",
    "moduleList": "Danh mục Module",
    "hrGroup": "Nhân sự & Tổ chức",
    "salaryGroup": "Tiền lương & Công",
    "systemGroup": "Hệ thống & Bảo mật",
    "setupTitle": "Thiết lập quyền:",
    "setupDesc": "Phân quyền chi tiết cho từng chức vụ đối với module này.",
    "position": "Chức vụ",
    "otherDept": "Khác",
    "admin": "Quản trị",
    "fullButton": "Full",
    "selectButton": "Chọn",
    "selectAll": "Chọn cả",
    "quickSelectFunction": "Lọc theo chức năng",
    "filterByDept": "Phòng ban",
    "filterByDeptAll": "Tất cả phòng"
  },
  "module": {
    "employeeList": "Danh sách Nhân viên",
    "departmentChart": "Sơ đồ Phòng ban",
    "positionRole": "Chức danh & Vị trí",
    "laborContract": "Hợp đồng lao động",
    "attendance": "Chấm công vân tay",
    "leaveRequest": "Đơn từ nghỉ phép",
    "payroll": "Tính lương & Thuế",
    "companyInfo": "Thông tin công ty",
    "generalConfig": "Cấu hình chung",
    "dataSecurity": "An toàn dữ liệu",
    "fullSystemDesc": "Toàn quyền hệ thống",
    "hrManagerDesc": "Quản lý và duyệt hồ sơ nhân sự",
    "undefined": "Chưa xác định",
    "jobLevel": "Cấp bậc",
    "branch": "Chi nhánh",
    "functionTask": "Chức năng nhiệm vụ",
    "loginDevice": "Thiết bị đăng nhập",
    "permission": "Phân quyền",
    "customers": "Danh sách khách hàng",
    "contacts": "Người liên hệ",
    "customerSettings": "Thiết lập khách hàng",
    "printMarkets": "Danh sách market in",
    "documentSettings": "Thiết lập tài liệu",
    "documentList": "Danh sách tài liệu",
    "payrollSettings": "Thiết lập công lương",
    "adminForms": "Phiếu hành chính",
    "contract": "Hợp đồng",
    "announcement": "Thông báo",
  },
  "validation": {
    "codeMin": "Mã vai trò tối thiểu 2 ký tự",
    "codeFormat": "Mã chỉ chứa chữ hoa, số và gạch dưới",
    "nameMin": "Tên vai trò quá ngắn",
    "descMax": "Mô tả tối đa 200 ký tự"
  },
  "store": {
    "roleCol": "Vai trò / Mã số",
    "descCol": "Mô tả chi tiết",
    "statsCol": "Thống kê",
    "statusCol": "Trạng thái",
    "logUserCol": "Người dùng / IP",
    "logActionCol": "Hành động",
    "logDeviceCol": "Thông tin thiết bị",
    "logTimeCol": "Thời gian",
    "logResultCol": "Kết quả"
  },
  "toast": {
    "createSuccess": "Đã tạo vai trò mới thành công",
    "deleteSuccess": "Đã xóa các vai trò được chọn",
    "updateSuccess": "Đã cập nhật phân quyền hệ thống"
  }
} as const;
