/** Chuỗi UI trang Tổng quan (dashboard + TV wallboard) */
export const overview = {
  title: 'Tổng quan',
  moduleDesc: 'Tổng hợp nhân sự và vận hành xưởng.',
  dashboardDesc: 'Thống kê nhân sự hôm nay và lối tắt sang màn hình Live TV.',
  liveTv: 'Live TV',
  liveTvHint: 'Mở màn hình chiếu toàn màn hình',
  exitTv: 'Thoát Live TV',
  hold: 'Giữ',
  holding: 'Đang giữ',
  releaseHold: 'Bỏ giữ',
  slideOf: '{{current}} / {{total}}',
  announcements: 'Thông báo',
  noAnnouncements: 'Chưa có thông báo trong ngày',
  updatedAt: 'Cập nhật lúc {{time}}',
  connectionLost: 'Mất kết nối · {{time}}',
  dataNote: 'Theo phiếu đã duyệt · chưa gồm chấm công',
  realtimeUpdate: 'Cập nhật theo thời gian thực',
  boardTitle: 'Bảng trạng thái nhân sự',
  weather: {
    clear: 'Trời quang',
    partlyCloudy: 'Ít mây',
    cloudy: 'Nhiều mây',
    fog: 'Sương mù',
    drizzle: 'Mưa phùn',
    rain: 'Mưa',
    showers: 'Mưa rào',
    snow: 'Tuyết',
    thunder: 'Dông',
    unavailable: '—',
    locationDefault: 'Bình Dương',
  },
  slides: {
    nhanSu: 'Nhân sự',
    sanXuat: 'Sản xuất',
    chatLuong: 'Chất lượng',
    anToan: 'An toàn & 5S',
  },
  kpi: {
    workforce: 'Tổng nhân sự',
    presentToday: 'Đang làm việc',
    onLeave: 'Nghỉ phép',
    onTrip: 'Đi công tác',
    probation: 'Thử việc',
  },
  table: {
    stt: 'STT',
    name: 'Họ và tên',
    position: 'Chức vụ',
    department: 'Bộ phận',
    status: 'Trạng thái',
    note: 'Ghi chú',
    empty: 'Chưa có dữ liệu nhân sự',
  },
  status: {
    lam_viec: 'Đang làm việc',
    cong_tac: 'Đi công tác',
    nghi: 'Nghỉ phép',
  },
  dashboard: {
    loading: 'Đang tải tổng quan…',
    sectionNav: 'Dữ liệu',
    sectionNhanSuDesc: 'Hiện diện nhân sự theo phiếu đã duyệt hôm nay.',
    byDepartment: 'Theo phòng ban',
    byPosition: 'Theo chức vụ',
    awayToday: 'Nghỉ / công tác hôm nay',
    emptyAway: 'Không có nghỉ phép hay công tác hôm nay',
    emptyDept: 'Chưa có dữ liệu phòng ban',
    emptyPosition: 'Chưa có dữ liệu chức vụ',
    noDepartment: 'Chưa gán phòng ban',
    noPosition: 'Chưa gán chức vụ',
    noDataFiltered: 'Không có bản ghi khớp bộ lọc hiện tại.',
    comingSoonGroup: 'Đang xây dựng',
    filterDepartment: 'Phòng ban',
    filterStatus: 'Trạng thái',
    colDepartment: 'Phòng ban',
    colPosition: 'Chức vụ',
    colTotal: 'Tổng',
    colPresent: 'Đang làm',
    colLeave: 'Nghỉ',
    colPresentRate: 'Tỷ lệ có mặt',
  },
  comingSoon: {
    badge: 'Đang xây dựng',
    badgeShort: 'Sắp có',
    sanXuatTitle: 'Sản xuất',
    sanXuatDesc:
      'Theo dõi lệnh sản xuất, tiến độ ca và vận hành máy sẽ hiển thị tại đây khi module sẵn sàng.',
    chatLuongTitle: 'Chất lượng',
    chatLuongDesc:
      'QC đầu vào, trong sản xuất và thành phẩm — tỷ lệ đạt, top lỗi sẽ được cập nhật sau.',
    anToanTitle: 'An toàn & 5S',
    anToanDesc:
      'Checklist khu vực, sự cố và chuỗi ngày an toàn sẽ xuất hiện trên màn hình này.',
  },
};
