/** Chữ giao diện dùng chung (nav, trang, lỗi, …) */
export const ui = {
  "nav": {
    "changePassword": {
      "title": "Đổi mật khẩu",
      "description": "Nhập mật khẩu hiện tại và mật khẩu mới để bảo mật tài khoản.",
      "currentPassword": "Mật khẩu hiện tại",
      "newPassword": "Mật khẩu mới",
      "confirmPassword": "Xác nhận mật khẩu mới",
      "showPassword": "Hiện mật khẩu",
      "hidePassword": "Ẩn mật khẩu",
      "newPasswordHint": "Ít nhất 1 ký tự (số hoặc chữ).",
      "submit": "Cập nhật mật khẩu",
      "success": "Đổi mật khẩu thành công.",
      "errorCurrentRequired": "Vui lòng nhập mật khẩu hiện tại.",
      "errorCurrentInvalid": "Mật khẩu hiện tại không đúng.",
      "errorNewMin": "Mật khẩu mới phải có ít nhất 1 ký tự (số hoặc chữ).",
      "errorConfirmMismatch": "Xác nhận mật khẩu không khớp.",
      "errorSameAsCurrent": "Mật khẩu mới phải khác mật khẩu hiện tại."
    },
    "home": "Trang chủ",
    "overview": "Tổng quan",
    "back": "Quay lại",
    "adminOps": "Hành chính",
    "business": "Kinh doanh",
    "production": "Sản xuất",
    "workItems": "Công việc",
    "system": "Hệ thống",
    "skipToMain": "Chuyển đến nội dung chính",
    "collapseSidebar": "Thu gọn sidebar",
    "expandSidebar": "Mở rộng sidebar",
    "closeOverlay": "Đóng overlay",
    "notification": "Thông báo",
    "userMenu": "Menu người dùng",
    "guestUser": "Guest User",
    "roleAdmin": "Admin",
    "roleMember": "Member",
    "profile": "Hồ sơ cá nhân",
    "logout": "Đăng xuất",
    "logoutConfirmTitle": "Xác nhận đăng xuất",
    "logoutConfirmMessage": "Bạn có chắc chắn muốn kết thúc phiên làm việc?",
    "logoutCancel": "Hủy bỏ",
    "defaultAppDescription": "Enterprise Platform",
    "mainNav": "Điều hướng chính",
    "changePasswordLabel": "Đổi mật khẩu",
    "commandPalette": {
      "title": "Điều hướng nhanh",
      "placeholder": "Tìm trang hoặc đường dẫn",
      "empty": "Không có kết quả",
      "hint": "Esc đóng · Enter mở · ↑↓ chọn",
      "groupGeneral": "Chung",
      "groupAdminOps": "Hành chính",
      "groupBusiness": "Kinh doanh",
      "groupProduction": "Sản xuất",
      "groupWorkItems": "Công việc",
      "groupSystem": "Hệ thống",
      "groupAccount": "Tài khoản"
    }
  },
  "shared": {
    "export": {
      "title": "Xuất dữ liệu",
      "format": "Định dạng",
      "scope": "Phạm vi",
      "scopeAll": "Tất cả",
      "scopeCurrentPage": "Trang hiện tại",
      "scopeSelected": "Đã chọn",
      "rows": "dòng",
      "selectColumns": "Chọn cột xuất",
      "deselectAll": "Bỏ chọn hết",
      "selectAll": "Chọn tất cả",
      "pdfHeader": "Xuất ngày: {{date}} | {{count}} bản ghi",
      "exporting": "Đang xuất...",
      "exportRows": "Xuất {{count}} dòng",
      "noData": "Không có dữ liệu để xuất",
      "failed": "Xuất dữ liệu thất bại. Vui lòng thử lại."
    },
    "import": {
      "title": "Import dữ liệu",
      "subtitle": "Tải lên file Excel hoặc CSV",
      "dropHere": "Kéo thả file vào đây",
      "orClickToSelect": "hoặc nhấn để chọn file (.xlsx, .xls, .csv)",
      "downloadTemplate": "Tải file mẫu (.xlsx)",
      "rowsRead": "Đã đọc {{count}} dòng dữ liệu",
      "systemColumn": "Cột hệ thống",
      "fileColumn": "Cột trong file",
      "skipColumn": "-- Bỏ qua --",
      "preview": "Xem trước (5 dòng đầu)",
      "success": "Import thành công!",
      "successCount": "{{count}} bản ghi đã được nhập",
      "error": "Không import được",
      "noDataOrHeader": "File không có dữ liệu hoặc thiếu header",
      "cannotReadFile": "Không thể đọc file. Vui lòng kiểm tra định dạng.",
      "missingRequiredColumns": "Chưa mapping cột bắt buộc: {{columns}}",
      "rowEmptyField": "\"{{column}}\" không được để trống",
      "noDataRows": "File không có dòng dữ liệu nào để import",
      "importError": "Lỗi khi import dữ liệu",
      "importRows": "Import {{count}} dòng",
      "processing": "Đang xử lý {{done}}/{{total}} dòng…",
      "partialSuccess": "Import hoàn tất một phần",
      "resultSummary": "Thành công: {{created}} · Lỗi: {{failed}}",
      "downloadErrorFile": "Tải file lỗi (.xlsx)",
      "moreErrors": "và {{count}} lỗi khác (xem file lỗi)",
      "errorColRow": "Dòng",
      "errorColMessage": "Lỗi",
      "templateGuideTitle": "Hướng dẫn import",
      "templateGuideIntro": "Chỉ nhập dữ liệu vào sheet \"Du_lieu\". Không sửa tên cột ở dòng 1.",
      "templateGuideRequired": "Cột bắt buộc (có dấu *):",
      "templateGuideDataSheet": "Sheet \"Du_lieu\": nhập dữ liệu từ dòng 3 trở đi (dòng 2 là gợi ý, có thể xóa).",
      "templateGuideLookup": "Sheet tra cứu — dùng để điền đúng mã/giá trị:",
      "templateRequiredHint": "(bắt buộc)"
    },
    "empty": {
      "title": "Không có dữ liệu",
      "description": "Chưa có dữ liệu. Thử thêm bản ghi hoặc điều chỉnh bộ lọc."
    },
    "error": {
      "title": "Đã xảy ra lỗi",
      "message": "Không thể tải dữ liệu. Vui lòng thử lại.",
      "retry": "Tải lại",
      "backHome": "Về trang chủ",
      "reloading": "Đang tải lại...",
      "network": "Lỗi kết nối mạng. Kiểm tra internet và thử lại.",
      "unauthorized": "Phiên đăng nhập hết hạn hoặc không có quyền truy cập.",
      "forbidden": "Bạn không có quyền thực hiện thao tác này.",
      "notFound": "Không tìm thấy tài nguyên.",
      "server": "Lỗi máy chủ. Vui lòng thử lại sau.",
      "timeout": "Hết thời gian chờ. Vui lòng thử lại.",
      "unknown": "Đã xảy ra lỗi không xác định. Vui lòng thử lại.",
      "beforeInitialization": "Lỗi khởi tạo: không thể truy cập trước khi khởi tạo. Vui lòng tải lại trang.",
      "notDefined": "Tham chiếu lỗi: thành phần chưa được định nghĩa. Vui lòng tải lại trang.",
      "notFunction": "Lỗi gọi hàm: giá trị không phải là hàm. Vui lòng tải lại trang.",
      "chunkLoad": "Không tải được phần mềm. Vui lòng tải lại trang.",
      "devDetail": "Chi tiết kỹ thuật (chế độ phát triển):"
    },
    "mobileFilter": {
      "title": "Bộ lọc",
      "searchPlaceholder": "Tìm {{label}}",
      "selectAll": "Chọn tất cả",
      "notFound": "Không tìm thấy",
      "clear": "Xóa bộ lọc"
    },
    "mobileActions": {
      "title": "Thao tác"
    },
    "toolbar": {
      "moreFilters": "Thêm bộ lọc"
    },
    "bulk": {
      "viewDetails": "Xem chi tiết",
      "partialTitle": "Kết quả xử lý hàng loạt",
      "failureRecord": "Bản ghi",
      "failureReason": "Lý do lỗi",
      "downloadFailures": "Tải danh sách lỗi (.xlsx)",
      "applyToCount": "Sẽ áp dụng cho {{count}} bản ghi",
      "skipCount": ", bỏ qua {{count}} bản ghi không đủ điều kiện",
      "notLoadedHint": "trong đó {{count}} bản ghi chưa tải — hệ thống sẽ kiểm tra khi thực hiện",
      "reasonRequired": "Vui lòng nhập lý do",
      "reasonPlaceholder": "Lý do áp dụng cho cả lô đã chọn"
    }
  },
  "page": {
    "home": {
      "greeting": "Xin chào,",
      "greetingMorning": "Chào buổi sáng",
      "greetingAfternoon": "Chào buổi chiều",
      "greetingEvening": "Chào buổi tối",
      "adminFallback": "Quản trị viên",
      "overviewModuleDesc": "Thống kê nhân sự hôm nay và màn hình Live TV.",
      "adminOpsModuleDesc": "Công văn, chấm công và nghiệp vụ hành chính.",
      "businessModuleDesc": "Bán hàng, khách hàng và cơ hội kinh doanh.",
      "productionModuleDesc": "Kế hoạch, sản xuất và quản lý kho.",
      "workItemsModuleDesc": "Công việc, nhiệm vụ và tài liệu liên quan.",
      "systemModuleDesc": "Cấu hình, phân quyền và nhân sự."
    },
    "placeholder": {
      "backToHome": "Quay lại trang chủ",
      "backToSubmenu": "Quay lại",
      "moduleComingSoon": "Chức năng đang được phát triển.",
      "title": "Module đang được phát triển",
      "description": "Chúng tôi đang nỗ lực hoàn thiện tính năng này để mang lại trải nghiệm tốt nhất cho bạn. Vui lòng quay lại sau!",
      "descriptionWithModule": "Tính năng {{name}} đang được hoàn thiện. Vui lòng quay lại sau!",
      "badgeComingSoon": "Sắp ra mắt",
      "refreshPage": "Làm mới trang",
      "expectedCompletion": "Dự kiến hoàn thành: Quý 2 - 2026",
      "exampleDoc": "Công văn",
      "exampleContract": "Hợp đồng",
      "exampleRecruit": "Tuyển dụng",
      "exampleAttendance": "Chấm công",
      "exampleCampaign": "Chiến dịch",
      "exampleAccounting": "Kế toán",
      "exampleOrder": "Đặt hàng",
      "exampleInventory": "Tồn kho"
    },
    "login": {
      "emailRequired": "Vui lòng nhập email",
      "emailInvalid": "Email không hợp lệ",
      "usernameRequired": "Vui lòng nhập tên tài khoản",
      "usernameMin": "Tên tài khoản phải có ít nhất 2 ký tự",
      "username": "Tên tài khoản",
      "passwordMin": "Vui lòng nhập mật khẩu",
      "mockUserName": "Lê Minh Công",
      "loginSuccess": "Đăng nhập thành công!",
      "googleUser": "Google User",
      "googleSuccess": "Đăng nhập bằng Google thành công!",
      "heading": "Quản lý doanh nghiệp",
      "headingHighlight": "thông minh & hiệu quả",
      "description": "Nền tảng tích hợp AI giúp tối ưu hóa quy trình nhân sự, tài chính và vận hành hệ thống của bạn trong một giao diện duy nhất.",
      "feature1": "Tích hợp AI Assistant mạnh mẽ",
      "feature2": "Dashboard phân tích dữ liệu Realtime",
      "feature3": "Bảo mật dữ liệu tiêu chuẩn Enterprise",
      "welcome": "Chào mừng trở lại",
      "welcomeDesc": "Nhập tên tài khoản và mật khẩu để truy cập.",
      "email": "Email",
      "emailPlaceholder": "VD: ten@congty.vn",
      "password": "Mật khẩu",
      "showPassword": "Hiện mật khẩu",
      "hidePassword": "Ẩn mật khẩu",
      "forgotPassword": "Quên mật khẩu?",
      "rememberMe": "Ghi nhớ đăng nhập",
      "rememberMeOnHint": "Duy trì đăng nhập 30 ngày trên thiết bị này.",
      "rememberMeOffHint": "Đóng trình duyệt là thoát đăng nhập.",
      "loginButton": "Đăng nhập",
      "orLoginWith": "Hoặc đăng nhập bằng",
      "forgotAccountLabel": "Tên tài khoản",
      "noAccount": "Bạn chưa có tài khoản?",
      "register": "Đăng ký ngay",
      "copyright": "© 2024",
      "companyFallback": "Phần mềm ERP",
      "legal": "Bảo mật • Điều khoản sử dụng",
      "forgotPasswordTitle": "Quên mật khẩu",
      "forgotPasswordDesc": "Tài khoản dùng email hệ thống (@gmail.com). Vui lòng liên hệ HR hoặc Quản trị để đặt lại mật khẩu.",
      "loginFailed": "Đăng nhập thất bại",
      "authConfigError": "Lỗi cấu hình máy chủ đăng nhập (AUTH_SECRET / kết nối Google Sheets). Kiểm tra log server hoặc liên hệ quản trị.",
      "accountNotFound": "Tài khoản không tồn tại. Kiểm tra lại tên đăng nhập hoặc liên hệ HR.",
      "wrongPassword": "Sai mật khẩu.",
      "employeeNotLinked": "Tài khoản chưa được gắn với hồ sơ nhân viên. Liên hệ quản trị.",
      "employeeResigned": "Nhân viên đã nghỉ việc — không thể đăng nhập.",
      "accountDisabled": "Tài khoản đã bị vô hiệu hóa",
      "noAuthAccount": "Chưa có tài khoản đăng nhập — liên hệ HR",
      "sendRecovery": "Liên hệ HR",
      "recoverySent": "Vui lòng liên hệ bộ phận Nhân sự hoặc Quản trị hệ thống để được hỗ trợ đặt lại mật khẩu.",
      "recoverySentTitle": "Khôi phục qua HR"
    },
    "forceChangePassword": {
      "title": "Đổi mật khẩu bắt buộc",
      "desc": "Đây là lần đăng nhập đầu tiên hoặc mật khẩu đã được HR đặt lại. Vui lòng chọn mật khẩu mới.",
      "newPassword": "Mật khẩu mới",
      "confirmPassword": "Xác nhận mật khẩu",
      "submit": "Cập nhật mật khẩu",
      "success": "Đã cập nhật mật khẩu thành công",
      "mismatch": "Mật khẩu xác nhận không khớp",
      "minLength": "Mật khẩu phải có ít nhất 1 ký tự (số hoặc chữ)"
    },
    "registerDisabled": {
      "title": "Đăng ký không khả dụng",
      "desc": "Tài khoản được HR/Quản trị tạo khi thêm nhân viên. Vui lòng liên hệ bộ phận Nhân sự.",
      "backToLogin": "Quay lại đăng nhập"
    },
    "register": {
      "title": "Tạo tài khoản",
      "desc": "Chỉ cần nhập tên đăng nhập (không cần @gmail.com — hệ thống tự thêm khi xác thực).",
      "fullName": "Họ và tên",
      "password": "Mật khẩu",
      "passwordHint": "Tối thiểu 1 ký tự (số hoặc chữ).",
      "confirmPassword": "Xác nhận mật khẩu",
      "submit": "Đăng ký",
      "success": "Đăng ký thành công! Bạn có thể đăng nhập ngay.",
      "passwordMismatch": "Mật khẩu xác nhận không khớp",
      "fullNameMin": "Họ tên phải có ít nhất 2 ký tự",
      "hasAccount": "Đã có tài khoản?",
      "loginLink": "Đăng nhập"
    },
    "profile": {
      "nameMin": "Tên phải có ít nhất 2 ký tự",
      "emailInvalid": "Địa chỉ email không hợp lệ",
      "bioMax": "Giới thiệu không được quá 160 ký tự",
      "defaultBio": "Lập trình viên Frontend | Đam mê công nghệ",
      "updateSuccess": "Cập nhật hồ sơ thành công!",
      "userNotFound": "Không tìm thấy thông tin người dùng.",
      "title": "Hồ sơ cá nhân",
      "description": "Quản lý thông tin tài khoản và cài đặt của bạn.",
      "activeStatus": "Đang hoạt động",
      "roleUser": "User",
      "joinedAt": "Tham gia",
      "verified": "Tài khoản xác thực",
      "avatarAlt": "Avatar của {{name}}",
      "avatarAltFallback": "Avatar người dùng",
      "basicInfo": "Thông tin cơ bản",
      "fullName": "Họ và tên",
      "email": "Email",
      "emailPlaceholder": "VD: ten@congty.vn",
      "bio": "Giới thiệu",
      "bioHint": "Tối đa 160 ký tự",
      "settingsSection": "Cài đặt",
      "emailNotification": "Thông báo qua Email",
      "emailNotificationDesc": "Nhận cập nhật về hoạt động tài khoản và tin tức mới nhất.",
      "viewOnlyBanner": "Bạn chỉ có quyền xem hồ sơ.",
      "changeAvatar": "Đổi ảnh đại diện",
      "changePassword": "Đổi mật khẩu",
      "changePasswordTitle": "Đổi mật khẩu",
      "changePasswordDesc": "Nhập mật khẩu hiện tại và mật khẩu mới.",
      "currentPassword": "Mật khẩu hiện tại",
      "newPassword": "Mật khẩu mới",
      "confirmPassword": "Xác nhận mật khẩu mới",
      "avatarModalTitle": "Đổi ảnh đại diện",
      "avatarModalHint": "Kéo thả hoặc chọn ảnh. PNG, JPG, tối đa 2MB.",
      "emptyField": "Chưa cập nhật",
      "detailSectionsTitle": "Thông tin chi tiết",
      "comingSoon": "Sắp ra mắt",
      "comingSoonDesc": "Tính năng đang được phát triển.",
      "avatarUpdateSuccess": "Đã cập nhật ảnh đại diện.",
      "wrongCurrentPassword": "Mật khẩu hiện tại không đúng.",
      "passwordChangeFailed": "Không thể đổi mật khẩu. Vui lòng thử lại.",
      "noLoginName": "Chưa có tên đăng nhập.",
      "dataSourceUnsupported": "Chế độ dữ liệu không hỗ trợ đổi mật khẩu."
    },
    "systemDashboard": {
      "orgChartGroup": "Sơ đồ",
      "employee": "Nhân viên",
      "employeeDesc": "Hồ sơ và thông tin nhân sự.",
      "department": "Phòng ban",
      "departmentDesc": "Cơ cấu tổ chức đơn vị.",
      "position": "Chức vụ",
      "positionDesc": "Quản lý các vị trí công việc.",
      "securityGroup": "Bảo mật & Cấu hình",
      "companyInfo": "Thông tin công ty",
      "companyInfoDesc": "Thiết lập thông tin pháp nhân.",
      "permission": "Phân quyền",
      "permissionDesc": "Vai trò và quyền hạn."
    },
    "businessDashboard": {
      "customerGroup": "Quản lý khách hàng",
      "customerList": "Danh sách khách hàng",
      "customerListDesc": "Hồ sơ và thông tin khách hàng.",
      "contact": "Người liên hệ",
      "contactDesc": "Danh bạ người liên hệ tại khách hàng.",
      "customerSettings": "Thiết lập khách hàng",
      "customerSettingsDesc": "Cấu hình phân loại và thuộc tính khách hàng."
    },
    "productionDashboard": {
      "productionInfoGroup": "Thông tin sản xuất",
      "printMarketList": "Danh sách market in",
      "printMarketListDesc": "Quản lý thông tin market in phục vụ sản xuất.",
      "blowingMachineParams": "Thông số vận hành máy thổi",
      "blowingMachineParamsDesc": "Theo dõi và cấu hình thông số vận hành máy thổi.",
      "cuttingMachineParams": "Thông số vận hành máy cắt",
      "cuttingMachineParamsDesc": "Theo dõi và cấu hình thông số vận hành máy cắt.",
      "pelletMixingFormula": "Công thức trộn hạt",
      "pelletMixingFormulaDesc": "Quản lý công thức trộn hạt dùng trong sản xuất."
    },
    "workDashboard": {
      "taskGroup": "Công việc",
      "task": "Công việc",
      "taskDesc": "Danh sách công việc đang xử lý.",
      "assignment": "Nhiệm vụ",
      "assignmentDesc": "Nhiệm vụ được giao và theo dõi tiến độ.",
      "taskStats": "Thống kê",
      "taskStatsDesc": "Báo cáo và thống kê công việc.",
      "docGroup": "Tài liệu",
      "documentList": "Danh sách tài liệu",
      "documentListDesc": "Quản lý tài liệu liên quan đến công việc.",
      "documentStats": "Thống kê",
      "documentStatsDesc": "Báo cáo và thống kê tài liệu."
    },
    "adminOpsDashboard": {
      "title": "Hành chính",
      "payrollGroup": "Công lương",
      "adminForm": "Phiếu hành chính",
      "adminFormDesc": "Tạo và duyệt các phiếu hành chính.",
      "adminFormStats": "Thống kê phiếu hành chính",
      "adminFormStatsDesc": "Báo cáo và thống kê phiếu hành chính.",
      "kpiScoring": "Chấm điểm KPI",
      "kpiScoringDesc": "Đánh giá KPI theo kỳ và tiêu chí.",
      "timesheet": "Bảng công",
      "timesheetDesc": "Tổng hợp chấm công theo kỳ.",
      "payroll": "Bảng lương",
      "payrollDesc": "Tính và quản lý bảng lương.",
      "payrollSettings": "Thiết lập công lương",
      "payrollSettingsDesc": "Cấu hình tham số công và lương.",
      "documentGroup": "Quản lý tài liệu",
      "documentList": "Danh sách tài liệu",
      "documentListDesc": "Kho tài liệu nội bộ và phân loại.",
      "documentStats": "Thống kê tài liệu",
      "documentStatsDesc": "Báo cáo và thống kê tài liệu.",
      "documentSettings": "Thiết lập tài liệu",
      "documentSettingsDesc": "Cấu hình danh mục và thuộc tính tài liệu.",
      "contractDecisionGroup": "Hợp đồng - Quyết định",
      "contract": "Hợp đồng",
      "contractDesc": "Quản lý hợp đồng nội bộ.",
      "decision": "Quyết định",
      "decisionDesc": "Quản lý quyết định hành chính.",
      "otherGroup": "Khác",
      "announcement": "Thông báo",
      "announcementDesc": "Quản lý thông báo nội bộ."
    }
  },

  "notification": {
    "title": "Thông báo",
    "developing": "Tính năng đang được phát triển.",
    "developingHint": "Chúng tôi đang nỗ lực hoàn thiện tính năng này. Vui lòng quay lại sau!",
    "markAllRead": "Đánh dấu tất cả đã đọc",
    "clearAll": "Xóa tất cả",
    "empty": "Chưa có thông báo",
    "emptyHint": "Các thông báo mới sẽ hiển thị tại đây.",
    "remove": "Xóa thông báo",
    "viewAll": "Xem tất cả thông báo",
    "collapse": "Thu gọn"
  },
  "breadcrumb": {
    "label": "Đường dẫn",
    "home": "Trang chủ",
    "overview": "Tổng quan",
    "liveTv": "Live TV",
    "goHome": "Về trang chủ",
    "systemAdmin": "Hệ thống",
    "adminOps": "Hành chính",
    "business": "Kinh doanh",
    "production": "Sản xuất",
    "workItems": "Công việc",
    "task": "Công việc",
    "assignment": "Nhiệm vụ",
    "taskStats": "Thống kê",
    "adminForm": "Phiếu hành chính",
    "adminFormStats": "Thống kê phiếu hành chính",
    "kpiScoring": "Chấm điểm KPI",
    "timesheet": "Bảng công",
    "payroll": "Bảng lương",
    "payrollSettings": "Thiết lập công lương",
    "documentList": "Danh sách tài liệu",
    "documentStats": "Thống kê tài liệu",
    "documentSettings": "Thiết lập tài liệu",
    "contract": "Hợp đồng",
    "decision": "Quyết định",
    "announcement": "Thông báo",
    "printMarketList": "Danh sách market in",
    "blowingMachineParams": "Thông số vận hành máy thổi",
    "cuttingMachineParams": "Thông số vận hành máy cắt",
    "pelletMixingFormula": "Công thức trộn hạt",
    "customerList": "Danh sách khách hàng",
    "contact": "Người liên hệ",
    "customerSettings": "Thiết lập khách hàng",
    "employee": "Nhân sự",
    "department": "Phòng ban",
    "position": "Chức vụ",
    "companyInfo": "Thông tin công ty",
    "permission": "Phân quyền",
    "profile": "Hồ sơ cá nhân",
    "moduleGuide": "Hướng dẫn"
  },
  "clock": {
    "sunday": "Chủ nhật",
    "monday": "Thứ 2",
    "tuesday": "Thứ 3",
    "wednesday": "Thứ 4",
    "thursday": "Thứ 5",
    "friday": "Thứ 6",
    "saturday": "Thứ 7"
  },
  "common": {
    "records": "bản ghi",
    "save": "Lưu",
    "required": "Trường bắt buộc",
    "saving": "Đang lưu...",
    "cancel": "Hủy",
    "close": "Đóng",
    "create": "Thêm",
    "view": "Xem",
    "edit": "Sửa",
    "duplicate": "Sao chép",
    "delete": "Xóa",
    "add": "Thêm",
    "confirm": "Xác nhận",
    "deleteAll": "Xóa tất cả",
    "deleteManyConfirm": "Xóa {{count}} bản ghi đã chọn?",
    "statusChangeManyConfirm": "Đổi trạng thái {{count}} bản ghi sang {{status}}?",
    "back": "Quay lại",
    "search": "Tìm kiếm",
    "searchPlaceholder": "Tìm kiếm",
    "searchShortcut": "Tìm kiếm (nhấn /)",
    "unknown": "Không xác định",
    "noData": "Không có dữ liệu",
    "noResults": "Không có kết quả phù hợp.",
    "loading": "Đang tải...",
    "active": "Hoạt động",
    "inactive": "Ngừng hoạt động",
    "status": "Trạng thái",
    "actions": "Thao tác",
    "moreRowActions": "Thao tác thêm",
    "description": "Mô tả",
    "all": "Tất cả",
    "perPage": "/ trang",
    "apply": "Áp dụng",
    "reset": "Khôi phục mặc định",
    "import": "Nhập",
    "export": "Xuất",
    "addNew": "Thêm",
    "activate": "Kích hoạt",
    "deactivate": "Tắt",
    "bulkChangeStatus": "Đổi trạng thái",
    "selected": "đã chọn",
    "selectedOnPage": "Đã chọn {{count}} bản ghi trên trang",
    "selectAll": "Chọn tất cả",
    "select": "Chọn",
    "deselectAll": "Bỏ chọn tất cả",
    "clearSelection": "Xóa chọn",
    "clearFilter": "Xóa bộ lọc",
    "clearFilters": "Xóa {{count}} bộ lọc",
    "columnDisplay": "Cột hiển thị",
    "columnOptions": "Tùy chọn cột",
    "densityCompact": "Gọn",
    "densityDefault": "Vừa",
    "densityComfortable": "Thoáng",
    "dragToReorderColumn": "Kéo để đổi thứ tự cột",
    "savedViews": "View đã lưu",
    "saveNewView": "Lưu view hiện tại",
    "viewNamePlaceholder": "Đặt tên cho view",
    "deleteView": "Xóa view",
    "noSavedViews": "Chưa có view nào được lưu",
    "viewSaved": "Đã lưu view",
    "viewApplied": "Đã áp dụng view",
    "viewDeleted": "Đã xóa view",
    "copyRow": "Sao chép hàng",
    "rowCopied": "Đã sao chép vào clipboard",
    "copyFailed": "Không thể sao chép",
    "printList": "In danh sách",
    "loadMore": "Xem thêm",
    "discardChangesTitle": "Hủy thay đổi chưa lưu?",
    "discardChangesMessage": "Bạn có thay đổi chưa lưu. Nếu đóng lại, mọi thay đổi sẽ bị mất.",
    "discardChangesConfirm": "Đóng, không lưu",
    "saveChanges": "Lưu",
    "cancelAction": "Hủy",
    "loadingData": "Đang tải dữ liệu",
    "processing": "Đang xử lý...",
    "finish": "Hoàn tất",
    "selectFile": "Chọn file khác",
    "allStatuses": "Tất cả trạng thái",
    "activeStatus": "Đang hoạt động",
    "inactiveStatus": "Ngừng hoạt động",
    "noDescription": "Không có mô tả",
    "error": "Đã xảy ra lỗi",
    "errorLoadData": "Không thể tải dữ liệu. Vui lòng thử lại.",
    "retry": "Thử lại",
    "firstPage": "Trang đầu",
    "prevPage": "Trang trước",
    "nextPage": "Trang sau",
    "lastPage": "Trang cuối",
    "doubleClickToPage": "Nhấn đúp để nhập trang"
  },
  "stats": {
    "columnLabel": "Tiêu đề",
    "columnValue": "Giá trị",
    "noData": "Không có dữ liệu",
    "footerRecords": "dòng",
    "trendVsLastPeriod": "So với kỳ trước",
    "drillDown": {
      "title": "Danh sách chi tiết",
      "subtitle": "{{count}} bản ghi · {{label}}",
      "showingFirst": "hiển thị {{count}} dòng đầu"
    }
  },
  "guide": {
    "buttonTitle": "Hướng dẫn",
    "pageTitle": "Hướng dẫn sử dụng",
    "backToModule": "Về module",
    "fallback": "Nội dung hướng dẫn đang được cập nhật.",
    "sections": {
      "overview": "Tổng quan",
      "permissions": "Phân quyền",
      "workflow": "Luồng thao tác",
      "quickStart": "Bắt đầu nhanh",
      "glossary": "Thuật ngữ",
      "faq": "Câu hỏi thường gặp",
      "contact": "Hỗ trợ"
    }
  },
  "field": {
    "selectEmpty": "— Chưa chọn —",
    "searchInList": "Tìm trong danh sách",
    "dropFile": "Kéo thả tệp hoặc bấm để chọn",
    "dropImage": "Kéo thả ảnh hoặc bấm để chọn",
    "pasteImageHint": "Có thể dán ảnh bằng Ctrl+V",
    "dateRangeFilter": "Khoảng thời gian"
  },
  "media": {
    "uploadError": "Không thể tải ảnh: {{message}}",
    "notImageFile": "File không phải ảnh",
    "readFileError": "Không thể đọc file",
    "sizeExceeded": "Ảnh vượt quá {{maxSizeMB}}MB",
    "defaultHint": "PNG, JPG, WebP · Tối đa {{maxSizeMB}}MB · Tự tối ưu khi tải lên",
    "dropHere": "Thả ảnh tại đây",
    "changeImage": "Đổi ảnh",
    "removeImage": "Xóa ảnh",
    "pickerTitle": "Chọn nguồn ảnh",
    "pickerGallery": "Chọn từ thư viện",
    "pickerGalleryHint": "Tải ảnh từ thiết bị",
    "pickerCamera": "Chụp ảnh",
    "pickerCameraHint": "Mở camera để chụp",
    "pickerCancel": "Hủy",
    "urlLabel": "Dán link ảnh",
    "urlPlaceholder": "https://…",
    "urlInvalid": "Link ảnh không hợp lệ (cần http hoặc https)",
    "urlLoadError": "Không tải được ảnh từ link",
    "multiDefaultHint": "PNG, JPG, WebP · Tối đa {{maxSizeMB}}MB/ảnh · Tự tối ưu khi tải lên",
    "multiAdd": "Thêm",
    "multiViewLarge": "Xem lớn",
    "multiFileNotImage": "\"{{fileName}}\" không phải ảnh",
    "multiFileSizeExceeded": "\"{{fileName}}\" vượt quá {{maxSizeMB}}MB",
    "multiRemainingLimit": "Chỉ thêm được {{count}} ảnh nữa",
    "multiMaxFilesReached": "Đã đạt số ảnh tối đa",
    "multiAddUrl": "Thêm link",
    "multiCount": "{{current}}/{{max}} ảnh"
  },
  "settings": {
    "primaryColor": "Màu",
    "colorBlue": "Xanh dương",
    "colorViolet": "Tím",
    "colorEmerald": "Xanh lá",
    "colorRose": "Hồng",
    "colorAmber": "Cam vàng",
    "colorOrange": "Cam",
    "colorCyan": "Xanh lơ",
    "colorSlate": "Xám"
  }
} as const;
